import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

const RootLayout = ({ children }: { children: React.ReactNode }) => (
  <html lang='en'>
    <body>{children}</body>
  </html>
)
export default RootLayout
