type ColorPalette = Record<string, string>;

const colors: ColorPalette  = {
    primary0: '#000',
    primary10: "#00201D",
    primary20: "#003732",
    primary30: "#005049",
    primary40: "#006A61",
    primary50: "#2E847A",
    primary60: "#4C9E94",
    primary70: "#68B9AE",
    primary80: "#84D5CA",
    primary90: "#A0F1E6",
    primary95: "#B3FFF3",
    primary99: "#F2FFFC",
    primary100: "#FFF",
    secondary0: "#000",
    secondary10: "#0E1E1C",
    secondary20: "#233331",
    secondary30: "#3A4A47",
    secondary40: "#51625F",
    secondary50: "#697B77",
    secondary60: "#839491",
    secondary70: "#9DAFAB",
    secondary80: "#B8CAC6",
    secondary90: "#D4E6E2",
    secondary95: "#E2F5F0",
    secondary99: "#F2FFFC",
    secondary100: "#FFF",
    tertiary0: "#000",
    tertiary10: "#0B1D2C",
    tertiary20: "#213241",
    tertiary30: "#374859",
    tertiary40: "#4F6071",
    tertiary50: "#67798B",
    tertiary60: "#8193A5",
    tertiary70: "#9BADC0",
    tertiary80: "#B6C8DC",
    tertiary90: "#D2E4F9",
    tertiary95: "#E7F2FF",
    tertiary99: "#FCFCFF",
    tertiary100: "#FFF",
    error0: "#000",
    error10: "#410002",
    error20: "#690005",
    error30: "#93000A",
    error40: "#BA1A1A",
    error50: "#DE3730",
    error60: "#FF5449",
    error70: "#FF897D",
    error80: "#FFB4AB",
    error90: "#FFDAD6",
    error95: "#FFEDEA",
    error99: "#FFFBFF",
    error100: "#FFF",
    neutral0: "#000",
    neutral4:"#090F0E",
    neutral6:"#0E1513",
    neutral10: "#1A1C1B",
    neutral12: "#1A2120",
    neutral17: "#252B2A",
    neutral20: "#2F3130",
    neutral22: "#303635",
    neutral24: "#343A39",
    neutral30: "#454746",
    neutral40: "#5D5F5E",
    neutral50: "#767776",
    neutral60: "#8F9190",
    neutral70: "#AAABAA",
    neutral80: "#AAABAA",
    neutral87: "#D5DBD9",
    neutral90: "#E2E3E1",
    neutral92: "#E3EAE7",
    neutral94: "#E9EFED",
    neutral95: "#F0F1EF",
    neutral96: "#EFF5F3",
    neutral98: "#F4FBF8",
    neutral99: "#F2FFFC",
    neutral100: "#FFF",
    neutralVariant0: "#000",
    neutralVariant10: "#171D1C",
    neutralVariant20: "#2B3230",
    neutralVariant30: "#454746",
    neutralVariant40: "#59605E",
    neutralVariant50: "#727877",
    neutralVariant60: "#8C9290",
    neutralVariant70: "#8C9290",
    neutralVariant80: "#C1C8C6",
    neutralVariant90: "#DEE4E1",
    neutralVariant95: "#ECF2F0",
    neutralVariant99: "#F2FFFC",
    neutralVariant100: "#FFF",
    white: "#FFF",
    gray950 : "#0C111D",
}


interface Theme {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    [key: string]: any;
    primary: Record<string, string>;
    secondary: Record<string, string>;
    tertiary: Record<string, string>;
    error: Record<string, string>;
}

const light: Theme = {
    onPrimary: colors.secondary100,
    primaryContainer: colors.primary90,
    onPrimaryContainer: colors.primary90,
    primaryFixed: colors.primary90,
    primaryFixedDim: colors.primary80,
    onPrimaryFixed: colors.primary10,
    onPrimaryFixedVariant: colors.primary30,
    surfaceDim: colors.neutral87,
    surface: colors.neutral98,
    surfaceBright: colors.neutral98,
    surfaceContainerLowest: colors.neutral100,
    surfaceContainerLow: colors.neutral96,
    surfaceContainer: colors.neutral94,
    surfaceContainerHigh: colors.neutral92,
    surfaceContainerHighest:colors.neutral90,
    onSurface: colors.neutral10,
    onSurfaceVariant: colors.neutralVariant30,
    outline: colors.neutralVariant50,
    outlineVariant : colors.neutralVariant80,
    onSecondary:  colors.secondary100,
    secondaryContainer: colors.secondary90,
    onSecondaryContainer: colors.secondary10,
    secondaryFixed: colors.secondary90,
    secondaryFixedDim: colors.secondary80,
    onSecondaryFixed: colors.secondary10,
    onSecondaryFixedVariant: colors.secondary30,
    onTertiary: colors.tertiary100,
    tertiaryContainer: colors.tertiary90,
    onTertiaryContainer: colors.tertiary10,
    tertiaryFixed: colors.tertiary90,
    tertiaryFixedDim: colors.tertiary80,
    onTertiaryFixed: colors.tertiary10,
    onTertiaryFixedVariant: colors.tertiary30,
    onError: colors.error100,
    errorContainer: colors.error90,
    onErrorContainer: colors.error10,
    inverseSurface: colors.neutral20,
    inverseOnSurface: colors.neutral95,
    inversePrimary: colors.primary80,
    scrim: colors.neutral0,
    shadows: colors.neutral0,
    white: colors.white,
    primary: {
        main: colors.primary40,
        light: colors.primary40,
        dark: colors.primary70,
    },
    secondary: {
        main: colors.secondary50,
        light: colors.secondary40,
        dark: colors.secondary70,
    },
    tertiary: {
        main: colors.tertiary50,
        light: colors.tertiary40,
        dark: colors.tertiary70,
    },
    error: {
        main: colors.error50,
        light: colors.error40,
        dark: colors.error70,
    },
}

const dark: Theme = {
    onPrimary: colors.secondary20,
    primaryContainer: colors.primary30,
    onPrimaryContainer: colors.primary90,
    primaryFixed: colors.primary90,
    primaryFixedDim: colors.primary80,
    onPrimaryFixed: colors.primary10,
    onPrimaryFixedVariant: colors.primary30,
    surfaceDim: colors.neutral6,
    surface: colors.neutral6,
    surfaceBright: colors.neutral24,
    surfaceContainerLowest: colors.neutral4,
    surfaceContainerLow: colors.neutral10,
    surfaceContainer: colors.neutral12,
    surfaceContainerHigh: colors.neutral17,
    surfaceContainerHighest: colors.neutral22,
    onSurface: colors.neutral90,
    onSurfaceVariant: colors.neutralVariant80,
    outline: colors.neutralVariant60,
    outlineVariant: colors.neutralVariant30,
    onSecondary: colors.secondary20,
    secondaryContainer: colors.secondary30,
    onSecondaryContainer: colors.secondary90,
    secondaryFixed: colors.secondary90,
    secondaryFixedDim: colors.secondary80,
    onSecondaryFixed: colors.secondary10,
    onSecondaryFixedVariant: colors.secondary30,
    onTertiary: colors.tertiary20,
    tertiaryContainer: colors.tertiary30,
    onTertiaryContainer: colors.tertiary90,
    tertiaryFixed: colors.tertiary90,
    tertiaryFixedDim: colors.tertiary80,
    onTertiaryFixed: colors.tertiary10,
    onTertiaryFixedVariant: colors.tertiary30,
    onError: colors.error80,
    errorContainer: colors.error30,
    onErrorContainer: colors.error90,
    inverseSurface: colors.neutral90,
    inverseOnSurface: colors.neutral20,
    inversePrimary: colors.primary40,
    scrim: colors.neutral0,
    shadows: colors.neutral0,
    white:  colors.white,
    primary: {
        main: colors.primary80,
        light: colors.primary40,
        dark: colors.primary80,
    },
    secondary: {
        main: colors.secondary50,
        light: colors.secondary40,
        dark: colors.secondary80,
    },
    tertiary: {
        main: colors.tertiary50,
        light: colors.tertiary40,
        dark: colors.tertiary80,
    },
    error: {
        main: colors.error50,
        light: colors.error40,
        dark: colors.error80,
    },
}


export {
    light,
    dark,
    colors
}
