/**
 * Static ISO 3166-1 alpha-2 country list with English and French display names.
 *
 * Backs the conference country selector for COMM/POSTER deposits. Only the (uppercase) `code` is
 * written to the TEI (`meeting/country/@key`, per HAL's convention); the localized name is UI-only.
 *
 * Codes are ISO 3166-1 alpha-2; names were generated once from `Intl.DisplayNames` (en, fr). Unlike
 * HAL domains (fetched from HAL's `/ref/domain/` API), HAL publishes **no** country referential — its
 * schema defines `country/@key` as a plain ISO 3166-1 code — so this list is intentionally static and
 * hand-maintained: add a code on the rare ISO addition, or adjust a name by hand. No generator, no
 * runtime API call.
 */

export interface HalCountry {
  /** ISO 3166-1 alpha-2 code — the only value emitted to the TEI. */
  code: string
  /** English display name. */
  en: string
  /** French display name. */
  fr: string
}

export const halCountries: readonly HalCountry[] = [
  { code: 'AF', en: 'Afghanistan', fr: 'Afghanistan' },
  { code: 'AX', en: 'Åland Islands', fr: 'Îles Åland' },
  { code: 'AL', en: 'Albania', fr: 'Albanie' },
  { code: 'DZ', en: 'Algeria', fr: 'Algérie' },
  { code: 'AS', en: 'American Samoa', fr: 'Samoa américaines' },
  { code: 'AD', en: 'Andorra', fr: 'Andorre' },
  { code: 'AO', en: 'Angola', fr: 'Angola' },
  { code: 'AI', en: 'Anguilla', fr: 'Anguilla' },
  { code: 'AQ', en: 'Antarctica', fr: 'Antarctique' },
  { code: 'AG', en: 'Antigua & Barbuda', fr: 'Antigua-et-Barbuda' },
  { code: 'AR', en: 'Argentina', fr: 'Argentine' },
  { code: 'AM', en: 'Armenia', fr: 'Arménie' },
  { code: 'AW', en: 'Aruba', fr: 'Aruba' },
  { code: 'AU', en: 'Australia', fr: 'Australie' },
  { code: 'AT', en: 'Austria', fr: 'Autriche' },
  { code: 'AZ', en: 'Azerbaijan', fr: 'Azerbaïdjan' },
  { code: 'BS', en: 'Bahamas', fr: 'Bahamas' },
  { code: 'BH', en: 'Bahrain', fr: 'Bahreïn' },
  { code: 'BD', en: 'Bangladesh', fr: 'Bangladesh' },
  { code: 'BB', en: 'Barbados', fr: 'Barbade' },
  { code: 'BY', en: 'Belarus', fr: 'Biélorussie' },
  { code: 'BE', en: 'Belgium', fr: 'Belgique' },
  { code: 'BZ', en: 'Belize', fr: 'Belize' },
  { code: 'BJ', en: 'Benin', fr: 'Bénin' },
  { code: 'BM', en: 'Bermuda', fr: 'Bermudes' },
  { code: 'BT', en: 'Bhutan', fr: 'Bhoutan' },
  { code: 'BO', en: 'Bolivia', fr: 'Bolivie' },
  { code: 'BA', en: 'Bosnia & Herzegovina', fr: 'Bosnie-Herzégovine' },
  { code: 'BW', en: 'Botswana', fr: 'Botswana' },
  { code: 'BV', en: 'Bouvet Island', fr: 'Île Bouvet' },
  { code: 'BR', en: 'Brazil', fr: 'Brésil' },
  {
    code: 'IO',
    en: 'British Indian Ocean Territory',
    fr: 'Territoire britannique de l’océan Indien',
  },
  { code: 'VG', en: 'British Virgin Islands', fr: 'Îles Vierges britanniques' },
  { code: 'BN', en: 'Brunei', fr: 'Brunei' },
  { code: 'BG', en: 'Bulgaria', fr: 'Bulgarie' },
  { code: 'BF', en: 'Burkina Faso', fr: 'Burkina Faso' },
  { code: 'BI', en: 'Burundi', fr: 'Burundi' },
  { code: 'KH', en: 'Cambodia', fr: 'Cambodge' },
  { code: 'CM', en: 'Cameroon', fr: 'Cameroun' },
  { code: 'CA', en: 'Canada', fr: 'Canada' },
  { code: 'CV', en: 'Cape Verde', fr: 'Cap-Vert' },
  { code: 'BQ', en: 'Caribbean Netherlands', fr: 'Pays-Bas caribéens' },
  { code: 'KY', en: 'Cayman Islands', fr: 'Îles Caïmans' },
  {
    code: 'CF',
    en: 'Central African Republic',
    fr: 'République centrafricaine',
  },
  { code: 'TD', en: 'Chad', fr: 'Tchad' },
  { code: 'CL', en: 'Chile', fr: 'Chili' },
  { code: 'CN', en: 'China', fr: 'Chine' },
  { code: 'CX', en: 'Christmas Island', fr: 'Île Christmas' },
  { code: 'CC', en: 'Cocos (Keeling) Islands', fr: 'Îles Cocos' },
  { code: 'CO', en: 'Colombia', fr: 'Colombie' },
  { code: 'KM', en: 'Comoros', fr: 'Comores' },
  { code: 'CG', en: 'Congo - Brazzaville', fr: 'Congo-Brazzaville' },
  { code: 'CD', en: 'Congo - Kinshasa', fr: 'Congo-Kinshasa' },
  { code: 'CK', en: 'Cook Islands', fr: 'Îles Cook' },
  { code: 'CR', en: 'Costa Rica', fr: 'Costa Rica' },
  { code: 'CI', en: 'Côte d’Ivoire', fr: 'Côte d’Ivoire' },
  { code: 'HR', en: 'Croatia', fr: 'Croatie' },
  { code: 'CU', en: 'Cuba', fr: 'Cuba' },
  { code: 'CW', en: 'Curaçao', fr: 'Curaçao' },
  { code: 'CY', en: 'Cyprus', fr: 'Chypre' },
  { code: 'CZ', en: 'Czechia', fr: 'Tchéquie' },
  { code: 'DK', en: 'Denmark', fr: 'Danemark' },
  { code: 'DJ', en: 'Djibouti', fr: 'Djibouti' },
  { code: 'DM', en: 'Dominica', fr: 'Dominique' },
  { code: 'DO', en: 'Dominican Republic', fr: 'République dominicaine' },
  { code: 'EC', en: 'Ecuador', fr: 'Équateur' },
  { code: 'EG', en: 'Egypt', fr: 'Égypte' },
  { code: 'SV', en: 'El Salvador', fr: 'Salvador' },
  { code: 'GQ', en: 'Equatorial Guinea', fr: 'Guinée équatoriale' },
  { code: 'ER', en: 'Eritrea', fr: 'Érythrée' },
  { code: 'EE', en: 'Estonia', fr: 'Estonie' },
  { code: 'SZ', en: 'Eswatini', fr: 'Eswatini' },
  { code: 'ET', en: 'Ethiopia', fr: 'Éthiopie' },
  { code: 'FK', en: 'Falkland Islands', fr: 'Îles Malouines' },
  { code: 'FO', en: 'Faroe Islands', fr: 'Îles Féroé' },
  { code: 'FJ', en: 'Fiji', fr: 'Fidji' },
  { code: 'FI', en: 'Finland', fr: 'Finlande' },
  { code: 'FR', en: 'France', fr: 'France' },
  { code: 'GF', en: 'French Guiana', fr: 'Guyane française' },
  { code: 'PF', en: 'French Polynesia', fr: 'Polynésie française' },
  {
    code: 'TF',
    en: 'French Southern Territories',
    fr: 'Terres australes françaises',
  },
  { code: 'GA', en: 'Gabon', fr: 'Gabon' },
  { code: 'GM', en: 'Gambia', fr: 'Gambie' },
  { code: 'GE', en: 'Georgia', fr: 'Géorgie' },
  { code: 'DE', en: 'Germany', fr: 'Allemagne' },
  { code: 'GH', en: 'Ghana', fr: 'Ghana' },
  { code: 'GI', en: 'Gibraltar', fr: 'Gibraltar' },
  { code: 'GR', en: 'Greece', fr: 'Grèce' },
  { code: 'GL', en: 'Greenland', fr: 'Groenland' },
  { code: 'GD', en: 'Grenada', fr: 'Grenade' },
  { code: 'GP', en: 'Guadeloupe', fr: 'Guadeloupe' },
  { code: 'GU', en: 'Guam', fr: 'Guam' },
  { code: 'GT', en: 'Guatemala', fr: 'Guatemala' },
  { code: 'GG', en: 'Guernsey', fr: 'Guernesey' },
  { code: 'GN', en: 'Guinea', fr: 'Guinée' },
  { code: 'GW', en: 'Guinea-Bissau', fr: 'Guinée-Bissau' },
  { code: 'GY', en: 'Guyana', fr: 'Guyana' },
  { code: 'HT', en: 'Haiti', fr: 'Haïti' },
  { code: 'HM', en: 'Heard & McDonald Islands', fr: 'Îles Heard-et-MacDonald' },
  { code: 'HN', en: 'Honduras', fr: 'Honduras' },
  { code: 'HK', en: 'Hong Kong SAR China', fr: 'R.A.S. chinoise de Hong Kong' },
  { code: 'HU', en: 'Hungary', fr: 'Hongrie' },
  { code: 'IS', en: 'Iceland', fr: 'Islande' },
  { code: 'IN', en: 'India', fr: 'Inde' },
  { code: 'ID', en: 'Indonesia', fr: 'Indonésie' },
  { code: 'IR', en: 'Iran', fr: 'Iran' },
  { code: 'IQ', en: 'Iraq', fr: 'Irak' },
  { code: 'IE', en: 'Ireland', fr: 'Irlande' },
  { code: 'IM', en: 'Isle of Man', fr: 'Île de Man' },
  { code: 'IL', en: 'Israel', fr: 'Israël' },
  { code: 'IT', en: 'Italy', fr: 'Italie' },
  { code: 'JM', en: 'Jamaica', fr: 'Jamaïque' },
  { code: 'JP', en: 'Japan', fr: 'Japon' },
  { code: 'JE', en: 'Jersey', fr: 'Jersey' },
  { code: 'JO', en: 'Jordan', fr: 'Jordanie' },
  { code: 'KZ', en: 'Kazakhstan', fr: 'Kazakhstan' },
  { code: 'KE', en: 'Kenya', fr: 'Kenya' },
  { code: 'KI', en: 'Kiribati', fr: 'Kiribati' },
  { code: 'KW', en: 'Kuwait', fr: 'Koweït' },
  { code: 'KG', en: 'Kyrgyzstan', fr: 'Kirghizstan' },
  { code: 'LA', en: 'Laos', fr: 'Laos' },
  { code: 'LV', en: 'Latvia', fr: 'Lettonie' },
  { code: 'LB', en: 'Lebanon', fr: 'Liban' },
  { code: 'LS', en: 'Lesotho', fr: 'Lesotho' },
  { code: 'LR', en: 'Liberia', fr: 'Liberia' },
  { code: 'LY', en: 'Libya', fr: 'Libye' },
  { code: 'LI', en: 'Liechtenstein', fr: 'Liechtenstein' },
  { code: 'LT', en: 'Lithuania', fr: 'Lituanie' },
  { code: 'LU', en: 'Luxembourg', fr: 'Luxembourg' },
  { code: 'MO', en: 'Macao SAR China', fr: 'R.A.S. chinoise de Macao' },
  { code: 'MG', en: 'Madagascar', fr: 'Madagascar' },
  { code: 'MW', en: 'Malawi', fr: 'Malawi' },
  { code: 'MY', en: 'Malaysia', fr: 'Malaisie' },
  { code: 'MV', en: 'Maldives', fr: 'Maldives' },
  { code: 'ML', en: 'Mali', fr: 'Mali' },
  { code: 'MT', en: 'Malta', fr: 'Malte' },
  { code: 'MH', en: 'Marshall Islands', fr: 'Îles Marshall' },
  { code: 'MQ', en: 'Martinique', fr: 'Martinique' },
  { code: 'MR', en: 'Mauritania', fr: 'Mauritanie' },
  { code: 'MU', en: 'Mauritius', fr: 'Maurice' },
  { code: 'YT', en: 'Mayotte', fr: 'Mayotte' },
  { code: 'MX', en: 'Mexico', fr: 'Mexique' },
  { code: 'FM', en: 'Micronesia', fr: 'Micronésie' },
  { code: 'MD', en: 'Moldova', fr: 'Moldavie' },
  { code: 'MC', en: 'Monaco', fr: 'Monaco' },
  { code: 'MN', en: 'Mongolia', fr: 'Mongolie' },
  { code: 'ME', en: 'Montenegro', fr: 'Monténégro' },
  { code: 'MS', en: 'Montserrat', fr: 'Montserrat' },
  { code: 'MA', en: 'Morocco', fr: 'Maroc' },
  { code: 'MZ', en: 'Mozambique', fr: 'Mozambique' },
  { code: 'MM', en: 'Myanmar (Burma)', fr: 'Myanmar (Birmanie)' },
  { code: 'NA', en: 'Namibia', fr: 'Namibie' },
  { code: 'NR', en: 'Nauru', fr: 'Nauru' },
  { code: 'NP', en: 'Nepal', fr: 'Népal' },
  { code: 'NL', en: 'Netherlands', fr: 'Pays-Bas' },
  { code: 'NC', en: 'New Caledonia', fr: 'Nouvelle-Calédonie' },
  { code: 'NZ', en: 'New Zealand', fr: 'Nouvelle-Zélande' },
  { code: 'NI', en: 'Nicaragua', fr: 'Nicaragua' },
  { code: 'NE', en: 'Niger', fr: 'Niger' },
  { code: 'NG', en: 'Nigeria', fr: 'Nigeria' },
  { code: 'NU', en: 'Niue', fr: 'Niue' },
  { code: 'NF', en: 'Norfolk Island', fr: 'Île Norfolk' },
  { code: 'KP', en: 'North Korea', fr: 'Corée du Nord' },
  { code: 'MK', en: 'North Macedonia', fr: 'Macédoine du Nord' },
  { code: 'MP', en: 'Northern Mariana Islands', fr: 'Îles Mariannes du Nord' },
  { code: 'NO', en: 'Norway', fr: 'Norvège' },
  { code: 'OM', en: 'Oman', fr: 'Oman' },
  { code: 'PK', en: 'Pakistan', fr: 'Pakistan' },
  { code: 'PW', en: 'Palau', fr: 'Palaos' },
  { code: 'PS', en: 'Palestinian Territories', fr: 'Territoires palestiniens' },
  { code: 'PA', en: 'Panama', fr: 'Panama' },
  { code: 'PG', en: 'Papua New Guinea', fr: 'Papouasie-Nouvelle-Guinée' },
  { code: 'PY', en: 'Paraguay', fr: 'Paraguay' },
  { code: 'PE', en: 'Peru', fr: 'Pérou' },
  { code: 'PH', en: 'Philippines', fr: 'Philippines' },
  { code: 'PN', en: 'Pitcairn Islands', fr: 'Îles Pitcairn' },
  { code: 'PL', en: 'Poland', fr: 'Pologne' },
  { code: 'PT', en: 'Portugal', fr: 'Portugal' },
  { code: 'PR', en: 'Puerto Rico', fr: 'Porto Rico' },
  { code: 'QA', en: 'Qatar', fr: 'Qatar' },
  { code: 'RE', en: 'Réunion', fr: 'La Réunion' },
  { code: 'RO', en: 'Romania', fr: 'Roumanie' },
  { code: 'RU', en: 'Russia', fr: 'Russie' },
  { code: 'RW', en: 'Rwanda', fr: 'Rwanda' },
  { code: 'WS', en: 'Samoa', fr: 'Samoa' },
  { code: 'SM', en: 'San Marino', fr: 'Saint-Marin' },
  { code: 'ST', en: 'São Tomé & Príncipe', fr: 'Sao Tomé-et-Principe' },
  { code: 'SA', en: 'Saudi Arabia', fr: 'Arabie saoudite' },
  { code: 'SN', en: 'Senegal', fr: 'Sénégal' },
  { code: 'RS', en: 'Serbia', fr: 'Serbie' },
  { code: 'SC', en: 'Seychelles', fr: 'Seychelles' },
  { code: 'SL', en: 'Sierra Leone', fr: 'Sierra Leone' },
  { code: 'SG', en: 'Singapore', fr: 'Singapour' },
  { code: 'SX', en: 'Sint Maarten', fr: 'Saint-Martin (partie néerlandaise)' },
  { code: 'SK', en: 'Slovakia', fr: 'Slovaquie' },
  { code: 'SI', en: 'Slovenia', fr: 'Slovénie' },
  { code: 'SB', en: 'Solomon Islands', fr: 'Îles Salomon' },
  { code: 'SO', en: 'Somalia', fr: 'Somalie' },
  { code: 'ZA', en: 'South Africa', fr: 'Afrique du Sud' },
  {
    code: 'GS',
    en: 'South Georgia & South Sandwich Islands',
    fr: 'Géorgie du Sud-et-les Îles Sandwich du Sud',
  },
  { code: 'KR', en: 'South Korea', fr: 'Corée du Sud' },
  { code: 'SS', en: 'South Sudan', fr: 'Soudan du Sud' },
  { code: 'ES', en: 'Spain', fr: 'Espagne' },
  { code: 'LK', en: 'Sri Lanka', fr: 'Sri Lanka' },
  { code: 'BL', en: 'St. Barthélemy', fr: 'Saint-Barthélemy' },
  { code: 'SH', en: 'St. Helena', fr: 'Sainte-Hélène' },
  { code: 'KN', en: 'St. Kitts & Nevis', fr: 'Saint-Christophe-et-Niévès' },
  { code: 'LC', en: 'St. Lucia', fr: 'Sainte-Lucie' },
  { code: 'MF', en: 'St. Martin', fr: 'Saint-Martin' },
  { code: 'PM', en: 'St. Pierre & Miquelon', fr: 'Saint-Pierre-et-Miquelon' },
  {
    code: 'VC',
    en: 'St. Vincent & Grenadines',
    fr: 'Saint-Vincent-et-les Grenadines',
  },
  { code: 'SD', en: 'Sudan', fr: 'Soudan' },
  { code: 'SR', en: 'Suriname', fr: 'Suriname' },
  { code: 'SJ', en: 'Svalbard & Jan Mayen', fr: 'Svalbard et Jan Mayen' },
  { code: 'SE', en: 'Sweden', fr: 'Suède' },
  { code: 'CH', en: 'Switzerland', fr: 'Suisse' },
  { code: 'SY', en: 'Syria', fr: 'Syrie' },
  { code: 'TW', en: 'Taiwan', fr: 'Taïwan' },
  { code: 'TJ', en: 'Tajikistan', fr: 'Tadjikistan' },
  { code: 'TZ', en: 'Tanzania', fr: 'Tanzanie' },
  { code: 'TH', en: 'Thailand', fr: 'Thaïlande' },
  { code: 'TL', en: 'Timor-Leste', fr: 'Timor oriental' },
  { code: 'TG', en: 'Togo', fr: 'Togo' },
  { code: 'TK', en: 'Tokelau', fr: 'Tokelau' },
  { code: 'TO', en: 'Tonga', fr: 'Tonga' },
  { code: 'TT', en: 'Trinidad & Tobago', fr: 'Trinité-et-Tobago' },
  { code: 'TN', en: 'Tunisia', fr: 'Tunisie' },
  { code: 'TR', en: 'Türkiye', fr: 'Turquie' },
  { code: 'TM', en: 'Turkmenistan', fr: 'Turkménistan' },
  { code: 'TC', en: 'Turks & Caicos Islands', fr: 'Îles Turques-et-Caïques' },
  { code: 'TV', en: 'Tuvalu', fr: 'Tuvalu' },
  {
    code: 'UM',
    en: 'U.S. Outlying Islands',
    fr: 'Îles mineures éloignées des États-Unis',
  },
  { code: 'VI', en: 'U.S. Virgin Islands', fr: 'Îles Vierges des États-Unis' },
  { code: 'UG', en: 'Uganda', fr: 'Ouganda' },
  { code: 'UA', en: 'Ukraine', fr: 'Ukraine' },
  { code: 'AE', en: 'United Arab Emirates', fr: 'Émirats arabes unis' },
  { code: 'GB', en: 'United Kingdom', fr: 'Royaume-Uni' },
  { code: 'US', en: 'United States', fr: 'États-Unis' },
  { code: 'UY', en: 'Uruguay', fr: 'Uruguay' },
  { code: 'UZ', en: 'Uzbekistan', fr: 'Ouzbékistan' },
  { code: 'VU', en: 'Vanuatu', fr: 'Vanuatu' },
  { code: 'VA', en: 'Vatican City', fr: 'État de la Cité du Vatican' },
  { code: 'VE', en: 'Venezuela', fr: 'Venezuela' },
  { code: 'VN', en: 'Vietnam', fr: 'Viêt Nam' },
  { code: 'WF', en: 'Wallis & Futuna', fr: 'Wallis-et-Futuna' },
  { code: 'EH', en: 'Western Sahara', fr: 'Sahara occidental' },
  { code: 'YE', en: 'Yemen', fr: 'Yémen' },
  { code: 'ZM', en: 'Zambia', fr: 'Zambie' },
  { code: 'ZW', en: 'Zimbabwe', fr: 'Zimbabwe' },
]

/** Lookup by ISO code. */
export const halCountriesByCode: Readonly<Record<string, HalCountry>> =
  Object.freeze(Object.fromEntries(halCountries.map((c) => [c.code, c])))

/** Localized display name for a country code (`fr` when locale starts with `fr`, else `en`). */
export const countryLabel = (code: string, locale: string): string => {
  const country = halCountriesByCode[code]
  if (!country) return code
  return locale.toLowerCase().startsWith('fr') ? country.fr : country.en
}
