export enum LocRelator {
  FORMER_OWNER = 'former owner',
  AUDIO_ENGINEER = 'audio engineer',
  DESIGNER = 'designer',
  SPEAKER = 'speaker',
  BOOKPLATE_DESIGNER = 'bookplate designer',
  PRODUCTION_COMPANY = 'production company',
  DISSERTANT = 'dissertant',
  MUSICIAN = 'musician',
  COLLECTION_REGISTRAR = 'collection registrar',
  BOOK_ARTIST = 'book artist',
  RESPONDENT_APPELLEE = 'respondent-appellee',
  PLAINTIFF = 'plaintiff',
  ENGRAVER = 'engraver',
  CONCEPTOR = 'conceptor',
  GEOGRAPHIC_INFORMATION_SPECIALIST = 'geographic information specialist',
  PRINTER = 'printer',
  APPLICANT = 'applicant',
  COPYRIGHT_CLAIMANT = 'copyright claimant',
  LIBELANT = 'libelant',
  APPELLEE = 'appellee',
  HONOREE = 'honoree',
  COMPLAINANT_APPELLANT = 'complainant-appellant',
  ORGANIZER = 'organizer',
  BRAILLE_EMBOSSER = 'braille embosser',
  ADAPTER = 'adapter',
  WRITER_OF_INTRODUCTION = 'writer of introduction',
  LITHOGRAPHER = 'lithographer',
  FUNDER = 'funder',
  CORRECTOR = 'corrector',
  VOICE_ACTOR = 'voice actor',
  WOOD_ENGRAVER = 'wood engraver',
  ANIMATOR = 'animator',
  MONITOR = 'monitor',
  ELECTROTYPER = 'electrotyper',
  ASSOCIATED_NAME = 'associated name',
  TELEVISION_PRODUCER = 'television producer',
  ORIGINATOR = 'originator',
  STAGE_DIRECTOR = 'stage director',
  COMPILER = 'compiler',
  INSCRIBER = 'inscriber',
  CREATOR = 'creator',
  MANUFACTURER = 'manufacturer',
  MODERATOR = 'moderator',
  FILM_DIRECTOR = 'film director',
  COMPOSER = 'composer',
  DATA_CONTRIBUTOR = 'data contributor',
  SCENARIST = 'scenarist',
  TYPE_DESIGNER = 'type designer',
  PRODUCER = 'producer',
  DELINEATOR = 'delineator',
  TECHNICAL_ADVISOR = 'technical advisor',
  CONTESTANT = 'contestant',
  CLIENT = 'client',
  PROCESS_CONTACT = 'process contact',
  TRANSLATOR = 'translator',
  PRODUCTION_MANAGER = 'production manager',
  MINUTE_TAKER = 'minute taker',
  PUBLISHER = 'publisher',
  ANNOTATOR = 'annotator',
  TELEVISION_WRITER = 'television writer',
  LIBELEE = 'libelee',
  AUDIO_PRODUCER = 'audio producer',
  ARRANGER = 'arranger',
  ENACTING_JURISDICTION = 'enacting jurisdiction',
  COSTUME_DESIGNER = 'costume designer',
  METAL_ENGRAVER = 'metal engraver',
  TELEVISION_DIRECTOR = 'television director',
  WRITER_OF_ADDED_LYRICS = 'writer of added lyrics',
  COPYRIGHT_HOLDER = 'copyright holder',
  CHOREOGRAPHER = 'choreographer',
  STORYTELLER = 'storyteller',
  METADATA_CONTACT = 'metadata contact',
  REVIEWER = 'reviewer',
  LICENSEE = 'licensee',
  COLLOTYPER = 'collotyper',
  INTERVIEWER = 'interviewer',
  ILLUSTRATOR = 'illustrator',
  ARCHITECT = 'architect',
  LIBELEE_APPELLEE = 'libelee-appellee',
  CONTESTEE = 'contestee',
  ART_DIRECTOR = 'art director',
  ELECTRICIAN = 'electrician',
  ONSCREEN_PRESENTER = 'onscreen presenter',
  BIBLIOGRAPHIC_ANTECEDENT = 'bibliographic antecedent',
  ADDRESSEE = 'addressee',
  ANNOUNCER = 'announcer',
  TELEVISION_HOST = 'television host',
  SOUND_ENGINEER = 'sound engineer',
  DRAFTSMAN = 'draftsman',
  STAGE_MANAGER = 'stage manager',
  ILLUMINATOR = 'illuminator',
  PUBLISHER_DIRECTOR = 'publisher director',
  ATTRIBUTED_NAME = 'attributed name',
  LABORATORY_DIRECTOR = 'laboratory director',
  PROGRAMMER = 'programmer',
  SINGER = 'singer',
  WRITER_OF_ACCOMPANYING_MATERIAL = 'writer of accompanying material',
  SELLER = 'seller',
  RESTORATIONIST = 'restorationist',
  ABRIDGER = 'abridger',
  HOST = 'host',
  RESTAGER = 'restager',
  PRINTMAKER = 'printmaker',
  DEDICATOR = 'dedicator',
  RECORDIST = 'recordist',
  UNIVERSITY_PLACE = 'university place',
  RESEARCH_TEAM_HEAD = 'research team head',
  CONTRIBUTOR = 'contributor',
  PATRON = 'patron',
  SURVEYOR = 'surveyor',
  TEACHER = 'teacher',
  AUTHOR_OF_DIALOG = 'author of dialog',
  WRITER_OF_PREFACE = 'writer of preface',
  CENSOR = 'censor',
  PRODUCTION_DESIGNER = 'production designer',
  ARTIST = 'artist',
  MUSIC_COPYIST = 'music copyist',
  PANELIST = 'panelist',
  SETTING = 'setting',
  MANUFACTURE_PLACE = 'manufacture place',
  APPELLANT = 'appellant',
  PLAINTIFF_APPELLEE = 'plaintiff-appellee',
  EDITOR_OF_MOVING_IMAGE_WORK = 'editor of moving image work',
  WITNESS = 'witness',
  ACTOR = 'actor',
  REPORTER = 'reporter',
  STANDARDS_BODY = 'standards body',
  INTERVIEWEE = 'interviewee',
  VISUAL_EFFECTS_PROVIDER = 'visual effects provider',
  AUTHOR_OF_INTRODUCTION__ETC_ = 'author of introduction, etc.',
  LANDSCAPE_ARCHITECT = 'landscape architect',
  AUCTIONEER = 'auctioneer',
  SIGNER = 'signer',
  CONTESTEE_APPELLANT = 'contestee-appellant',
  PROJECT_DIRECTOR = 'project director',
  CINEMATOGRAPHER = 'cinematographer',
  JUDGE = 'judge',
  LEAD = 'lead',
  COLLECTOR = 'collector',
  BROADCASTER = 'broadcaster',
  OWNER = 'owner',
  DEFENDANT_APPELLEE = 'defendant-appellee',
  NARRATOR = 'narrator',
  COMPOSITOR = 'compositor',
  LIBELANT_APPELLANT = 'libelant-appellant',
  DANCER = 'dancer',
  ETCHER = 'etcher',
  FILM_EDITOR = 'film editor',
  LIBRETTIST = 'librettist',
  RADIO_PRODUCER = 'radio producer',
  EXPERT = 'expert',
  RECORDING_ENGINEER = 'recording engineer',
  SUPPORTING_HOST = 'supporting host',
  DEDICATEE = 'dedicatee',
  RUBRICATOR = 'rubricator',
  PRAESES = 'praeses',
  COURT_GOVERNED = 'court governed',
  CONTESTANT_APPELLEE = 'contestant-appellee',
  RESPONSIBLE_PARTY = 'responsible party',
  AUTHOR = 'author',
  MIXING_ENGINEER = 'mixing engineer',
  INSTRUMENTALIST = 'instrumentalist',
  MUSICAL_DIRECTOR = 'musical director',
  DEGREE_GRANTING_INSTITUTION = 'degree granting institution',
  SPONSOR = 'sponsor',
  DIRECTOR = 'director',
  DISTRIBUTION_PLACE = 'distribution place',
  JURISDICTION_GOVERNED = 'jurisdiction governed',
  DJ = 'dj',
  CONSULTANT_TO_A_PROJECT = 'consultant to a project',
  RESPONDENT_APPELLANT = 'respondent-appellant',
  BINDING_DESIGNER = 'binding designer',
  RADIO_DIRECTOR = 'radio director',
  CURATOR = 'curator',
  THESIS_ADVISOR = 'thesis advisor',
  EDITORIAL_DIRECTOR = 'editorial director',
  WRITER_OF_ADDED_COMMENTARY = 'writer of added commentary',
  BOOK_DESIGNER = 'book designer',
  MUSIC_PROGRAMMER = 'music programmer',
  LENDER = 'lender',
  COMPLAINANT = 'complainant',
  SPECIAL_EFFECTS_PROVIDER = 'special effects provider',
  PLACE_OF_ADDRESS = 'place of address',
  PROOFREADER = 'proofreader',
  LIBELEE_APPELLANT = 'libelee-appellant',
  COMMENTATOR_FOR_WRITTEN_TEXT = 'commentator for written text',
  AUTHOR_OF_AFTERWORD__COLOPHON__ETC_ = 'author of afterword, colophon, etc.',
  COLORIST = 'colorist',
  SECOND_PARTY = 'second party',
  DEGREE_SUPERVISOR = 'degree supervisor',
  BINDER = 'binder',
  LYRICIST = 'lyricist',
  AUTHOR_IN_QUOTATIONS_OR_TEXT_ABSTRACTS = 'author in quotations or text abstracts',
  RENDERER = 'renderer',
  MARKUP_EDITOR = 'markup editor',
  DEFENDANT = 'defendant',
  PERFORMER = 'performer',
  AUTOGRAPHER = 'autographer',
  HOST_INSTITUTION = 'host institution',
  SET_DESIGNER = 'set designer',
  FOUNDER = 'founder',
  DUBIOUS_AUTHOR = 'dubious author',
  PATENT_HOLDER = 'patent holder',
  TECHNICAL_DIRECTOR = 'technical director',
  INVENTOR = 'inventor',
  TYPOGRAPHER = 'typographer',
  ASSIGNEE = 'assignee',
  WRITER_OF_ADDED_TEXT = 'writer of added text',
  CAMERA_OPERATOR = 'camera operator',
  SCREENWRITER = 'screenwriter',
  COMMENTATOR = 'commentator',
  ARTISTIC_DIRECTOR = 'artistic director',
  BOOKSELLER = 'bookseller',
  EDITOR = 'editor',
  BOOK_PRODUCER = 'book producer',
  VIDEOGRAPHER = 'videographer',
  CALLIGRAPHER = 'calligrapher',
  PLAINTIFF_APPELLANT = 'plaintiff-appellant',
  WOODCUTTER = 'woodcutter',
  RESEARCH_TEAM_MEMBER = 'research team member',
  CARTOGRAPHER = 'cartographer',
  ENGINEER = 'engineer',
  MAKEUP_ARTIST = 'makeup artist',
  RESEARCHER = 'researcher',
  CONTRACTOR = 'contractor',
  CASTING_DIRECTOR = 'casting director',
  COVER_DESIGNER = 'cover designer',
  FORGER = 'forger',
  TRANSCRIBER = 'transcriber',
  COMPLAINANT_APPELLEE = 'complainant-appellee',
  TELEVISION_GUEST = 'television guest',
  PRINTER_OF_PLATES = 'printer of plates',
  DUBBING_DIRECTOR = 'dubbing director',
  REPOSITORY = 'repository',
  LICENSOR = 'licensor',
  FILM_DISTRIBUTOR = 'film distributor',
  REDAKTOR = 'redaktor',
  DEGREE_COMMITTEE_MEMBER = 'degree committee member',
  PUPPETEER = 'puppeteer',
  STEREOTYPER = 'stereotyper',
  DEFENDANT_APPELLANT = 'defendant-appellant',
  CORRESPONDENT = 'correspondent',
  ISSUING_BODY = 'issuing body',
  RAPPORTEUR = 'rapporteur',
  CONSERVATOR = 'conservator',
  WRITER_OF_SUPPLEMENTARY_TEXTUAL_CONTENT = 'writer of supplementary textual content',
  SCRIBE = 'scribe',
  ART_COPYIST = 'art copyist',
  VOCALIST = 'vocalist',
  SOFTWARE_DEVELOPER = 'software developer',
  LABORATORY = 'laboratory',
  CONSULTANT = 'consultant',
  SCIENTIFIC_ADVISOR = 'scientific advisor',
  DEPOSITOR = 'depositor',
  SOUND_DESIGNER = 'sound designer',
  BOOKJACKET_DESIGNER = 'bookjacket designer',
  EDITOR_OF_COMPILATION = 'editor of compilation',
  DEPICTED = 'depicted',
  FACSIMILIST = 'facsimilist',
  SCULPTOR = 'sculptor',
  DISTRIBUTOR = 'distributor',
  LIBELANT_APPELLEE = 'libelant-appellee',
  WRITER_OF_INTERTITLES = 'writer of intertitles',
  CONTESTANT_APPELLANT = 'contestant-appellant',
  PRODUCTION_PLACE = 'production place',
  SECRETARY = 'secretary',
  FILM_PRODUCER = 'film producer',
  ONSCREEN_PARTICIPANT = 'onscreen participant',
  BLURB_WRITER = 'blurb writer',
  WRITER_OF_TELEVISION_STORY = 'writer of television story',
  CASTER = 'caster',
  PROVIDER = 'provider',
  PUBLICATION_PLACE = 'publication place',
  LIGHTING_DESIGNER = 'lighting designer',
  OTHER = 'other',
  PLATEMAKER = 'platemaker',
  MARBLER = 'marbler',
  CONTESTEE_APPELLEE = 'contestee-appellee',
  FIELD_DIRECTOR = 'field director',
  WRITER_OF_FILM_STORY = 'writer of film story',
  OPPONENT = 'opponent',
  ANALYST = 'analyst',
  PERMITTING_AGENCY = 'permitting agency',
  REMIX_ARTIST = 'remix artist',
  PRESENTER = 'presenter',
  PHOTOGRAPHER = 'photographer',
  PATENT_APPLICANT = 'patent applicant',
  DONOR = 'donor',
  MEDIUM = 'medium',
  EVENT_PLACE = 'event place',
  CONDUCTOR = 'conductor',
  GAME_DEVELOPER = 'game developer',
  DATA_MANAGER = 'data manager',
  LETTERER = 'letterer',
  PAPERMAKER = 'papermaker',
  FIRST_PARTY = 'first party',
  RESPONDENT = 'respondent',
  NEWS_ANCHOR = 'news anchor',
  COURT_REPORTER = 'court reporter',
  PRODUCTION_PERSONNEL = 'production personnel',
  FILMMAKER = 'filmmaker',
}

export class LocRelatorHelper {
  private static readonly uriToRelatorMap: Record<string, LocRelator> = {
    'http://id.loc.gov/vocabulary/relators/fmo': LocRelator.FORMER_OWNER,
    'http://id.loc.gov/vocabulary/relators/aue': LocRelator.AUDIO_ENGINEER,
    'http://id.loc.gov/vocabulary/relators/dsr': LocRelator.DESIGNER,
    'http://id.loc.gov/vocabulary/relators/spk': LocRelator.SPEAKER,
    'http://id.loc.gov/vocabulary/relators/bpd': LocRelator.BOOKPLATE_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/prn': LocRelator.PRODUCTION_COMPANY,
    'http://id.loc.gov/vocabulary/relators/dis': LocRelator.DISSERTANT,
    'http://id.loc.gov/vocabulary/relators/mus': LocRelator.MUSICIAN,
    'http://id.loc.gov/vocabulary/relators/cor':
      LocRelator.COLLECTION_REGISTRAR,
    'http://id.loc.gov/vocabulary/relators/bka': LocRelator.BOOK_ARTIST,
    'http://id.loc.gov/vocabulary/relators/rse': LocRelator.RESPONDENT_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/ptf': LocRelator.PLAINTIFF,
    'http://id.loc.gov/vocabulary/relators/egr': LocRelator.ENGRAVER,
    'http://id.loc.gov/vocabulary/relators/ccp': LocRelator.CONCEPTOR,
    'http://id.loc.gov/vocabulary/relators/gis':
      LocRelator.GEOGRAPHIC_INFORMATION_SPECIALIST,
    'http://id.loc.gov/vocabulary/relators/prt': LocRelator.PRINTER,
    'http://id.loc.gov/vocabulary/relators/app': LocRelator.APPLICANT,
    'http://id.loc.gov/vocabulary/relators/cpc': LocRelator.COPYRIGHT_CLAIMANT,
    'http://id.loc.gov/vocabulary/relators/lil': LocRelator.LIBELANT,
    'http://id.loc.gov/vocabulary/relators/ape': LocRelator.APPELLEE,
    'http://id.loc.gov/vocabulary/relators/hnr': LocRelator.HONOREE,
    'http://id.loc.gov/vocabulary/relators/cpt':
      LocRelator.COMPLAINANT_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/orm': LocRelator.ORGANIZER,
    'http://id.loc.gov/vocabulary/relators/brl': LocRelator.BRAILLE_EMBOSSER,
    'http://id.loc.gov/vocabulary/relators/adp': LocRelator.ADAPTER,
    'http://id.loc.gov/vocabulary/relators/win':
      LocRelator.WRITER_OF_INTRODUCTION,
    'http://id.loc.gov/vocabulary/relators/ltg': LocRelator.LITHOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/fnd': LocRelator.FUNDER,
    'http://id.loc.gov/vocabulary/relators/crr': LocRelator.CORRECTOR,
    'http://id.loc.gov/vocabulary/relators/vac': LocRelator.VOICE_ACTOR,
    'http://id.loc.gov/vocabulary/relators/wde': LocRelator.WOOD_ENGRAVER,
    'http://id.loc.gov/vocabulary/relators/anm': LocRelator.ANIMATOR,
    'http://id.loc.gov/vocabulary/relators/mon': LocRelator.MONITOR,
    'http://id.loc.gov/vocabulary/relators/elt': LocRelator.ELECTROTYPER,
    'http://id.loc.gov/vocabulary/relators/asn': LocRelator.ASSOCIATED_NAME,
    'http://id.loc.gov/vocabulary/relators/tlp': LocRelator.TELEVISION_PRODUCER,
    'http://id.loc.gov/vocabulary/relators/org': LocRelator.ORIGINATOR,
    'http://id.loc.gov/vocabulary/relators/sgd': LocRelator.STAGE_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/com': LocRelator.COMPILER,
    'http://id.loc.gov/vocabulary/relators/ins': LocRelator.INSCRIBER,
    'http://id.loc.gov/vocabulary/relators/cre': LocRelator.CREATOR,
    'http://id.loc.gov/vocabulary/relators/mfr': LocRelator.MANUFACTURER,
    'http://id.loc.gov/vocabulary/relators/mod': LocRelator.MODERATOR,
    'http://id.loc.gov/vocabulary/relators/fmd': LocRelator.FILM_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/cmp': LocRelator.COMPOSER,
    'http://id.loc.gov/vocabulary/relators/dtc': LocRelator.DATA_CONTRIBUTOR,
    'http://id.loc.gov/vocabulary/relators/sce': LocRelator.SCENARIST,
    'http://id.loc.gov/vocabulary/relators/tyd': LocRelator.TYPE_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/pro': LocRelator.PRODUCER,
    'http://id.loc.gov/vocabulary/relators/dln': LocRelator.DELINEATOR,
    'http://id.loc.gov/vocabulary/relators/tad': LocRelator.TECHNICAL_ADVISOR,
    'http://id.loc.gov/vocabulary/relators/cos': LocRelator.CONTESTANT,
    'http://id.loc.gov/vocabulary/relators/cli': LocRelator.CLIENT,
    'http://id.loc.gov/vocabulary/relators/prc': LocRelator.PROCESS_CONTACT,
    'http://id.loc.gov/vocabulary/relators/trl': LocRelator.TRANSLATOR,
    'http://id.loc.gov/vocabulary/relators/pmn': LocRelator.PRODUCTION_MANAGER,
    'http://id.loc.gov/vocabulary/relators/mtk': LocRelator.MINUTE_TAKER,
    'http://id.loc.gov/vocabulary/relators/pbl': LocRelator.PUBLISHER,
    'http://id.loc.gov/vocabulary/relators/ann': LocRelator.ANNOTATOR,
    'http://id.loc.gov/vocabulary/relators/tau': LocRelator.TELEVISION_WRITER,
    'http://id.loc.gov/vocabulary/relators/lel': LocRelator.LIBELEE,
    'http://id.loc.gov/vocabulary/relators/aup': LocRelator.AUDIO_PRODUCER,
    'http://id.loc.gov/vocabulary/relators/arr': LocRelator.ARRANGER,
    'http://id.loc.gov/vocabulary/relators/enj':
      LocRelator.ENACTING_JURISDICTION,
    'http://id.loc.gov/vocabulary/relators/cst': LocRelator.COSTUME_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/mte': LocRelator.METAL_ENGRAVER,
    'http://id.loc.gov/vocabulary/relators/tld': LocRelator.TELEVISION_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/wal':
      LocRelator.WRITER_OF_ADDED_LYRICS,
    'http://id.loc.gov/vocabulary/relators/cph': LocRelator.COPYRIGHT_HOLDER,
    'http://id.loc.gov/vocabulary/relators/chr': LocRelator.CHOREOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/stl': LocRelator.STORYTELLER,
    'http://id.loc.gov/vocabulary/relators/mdc': LocRelator.METADATA_CONTACT,
    'http://id.loc.gov/vocabulary/relators/rev': LocRelator.REVIEWER,
    'http://id.loc.gov/vocabulary/relators/lse': LocRelator.LICENSEE,
    'http://id.loc.gov/vocabulary/relators/clt': LocRelator.COLLOTYPER,
    'http://id.loc.gov/vocabulary/relators/ivr': LocRelator.INTERVIEWER,
    'http://id.loc.gov/vocabulary/relators/ill': LocRelator.ILLUSTRATOR,
    'http://id.loc.gov/vocabulary/relators/arc': LocRelator.ARCHITECT,
    'http://id.loc.gov/vocabulary/relators/lee': LocRelator.LIBELEE_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/cts': LocRelator.CONTESTEE,
    'http://id.loc.gov/vocabulary/relators/adi': LocRelator.ART_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/elg': LocRelator.ELECTRICIAN,
    'http://id.loc.gov/vocabulary/relators/osp': LocRelator.ONSCREEN_PRESENTER,
    'http://id.loc.gov/vocabulary/relators/ant':
      LocRelator.BIBLIOGRAPHIC_ANTECEDENT,
    'http://id.loc.gov/vocabulary/relators/rcp': LocRelator.ADDRESSEE,
    'http://id.loc.gov/vocabulary/relators/anc': LocRelator.ANNOUNCER,
    'http://id.loc.gov/vocabulary/relators/tlh': LocRelator.TELEVISION_HOST,
    'http://id.loc.gov/vocabulary/relators/sde': LocRelator.SOUND_ENGINEER,
    'http://id.loc.gov/vocabulary/relators/drm': LocRelator.DRAFTSMAN,
    'http://id.loc.gov/vocabulary/relators/stm': LocRelator.STAGE_MANAGER,
    'http://id.loc.gov/vocabulary/relators/ilu': LocRelator.ILLUMINATOR,
    'http://id.loc.gov/vocabulary/relators/pbd': LocRelator.PUBLISHER_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/att': LocRelator.ATTRIBUTED_NAME,
    'http://id.loc.gov/vocabulary/relators/ldr': LocRelator.LABORATORY_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/prg': LocRelator.PROGRAMMER,
    'http://id.loc.gov/vocabulary/relators/sng': LocRelator.SINGER,
    'http://id.loc.gov/vocabulary/relators/wam':
      LocRelator.WRITER_OF_ACCOMPANYING_MATERIAL,
    'http://id.loc.gov/vocabulary/relators/sll': LocRelator.SELLER,
    'http://id.loc.gov/vocabulary/relators/rsr': LocRelator.RESTORATIONIST,
    'http://id.loc.gov/vocabulary/relators/abr': LocRelator.ABRIDGER,
    'http://id.loc.gov/vocabulary/relators/hst': LocRelator.HOST,
    'http://id.loc.gov/vocabulary/relators/rsg': LocRelator.RESTAGER,
    'http://id.loc.gov/vocabulary/relators/prm': LocRelator.PRINTMAKER,
    'http://id.loc.gov/vocabulary/relators/dto': LocRelator.DEDICATOR,
    'http://id.loc.gov/vocabulary/relators/rcd': LocRelator.RECORDIST,
    'http://id.loc.gov/vocabulary/relators/uvp': LocRelator.UNIVERSITY_PLACE,
    'http://id.loc.gov/vocabulary/relators/rth': LocRelator.RESEARCH_TEAM_HEAD,
    'http://id.loc.gov/vocabulary/relators/ctb': LocRelator.CONTRIBUTOR,
    'http://id.loc.gov/vocabulary/relators/pat': LocRelator.PATRON,
    'http://id.loc.gov/vocabulary/relators/srv': LocRelator.SURVEYOR,
    'http://id.loc.gov/vocabulary/relators/tch': LocRelator.TEACHER,
    'http://id.loc.gov/vocabulary/relators/aud': LocRelator.AUTHOR_OF_DIALOG,
    'http://id.loc.gov/vocabulary/relators/wpr': LocRelator.WRITER_OF_PREFACE,
    'http://id.loc.gov/vocabulary/relators/cns': LocRelator.CENSOR,
    'http://id.loc.gov/vocabulary/relators/prs': LocRelator.PRODUCTION_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/art': LocRelator.ARTIST,
    'http://id.loc.gov/vocabulary/relators/mcp': LocRelator.MUSIC_COPYIST,
    'http://id.loc.gov/vocabulary/relators/pan': LocRelator.PANELIST,
    'http://id.loc.gov/vocabulary/relators/stg': LocRelator.SETTING,
    'http://id.loc.gov/vocabulary/relators/mfp': LocRelator.MANUFACTURE_PLACE,
    'http://id.loc.gov/vocabulary/relators/apl': LocRelator.APPELLANT,
    'http://id.loc.gov/vocabulary/relators/pte': LocRelator.PLAINTIFF_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/edm':
      LocRelator.EDITOR_OF_MOVING_IMAGE_WORK,
    'http://id.loc.gov/vocabulary/relators/wit': LocRelator.WITNESS,
    'http://id.loc.gov/vocabulary/relators/act': LocRelator.ACTOR,
    'http://id.loc.gov/vocabulary/relators/rpt': LocRelator.REPORTER,
    'http://id.loc.gov/vocabulary/relators/stn': LocRelator.STANDARDS_BODY,
    'http://id.loc.gov/vocabulary/relators/ive': LocRelator.INTERVIEWEE,
    'http://id.loc.gov/vocabulary/relators/vfx':
      LocRelator.VISUAL_EFFECTS_PROVIDER,
    'http://id.loc.gov/vocabulary/relators/aui':
      LocRelator.AUTHOR_OF_INTRODUCTION__ETC_,
    'http://id.loc.gov/vocabulary/relators/lsa': LocRelator.LANDSCAPE_ARCHITECT,
    'http://id.loc.gov/vocabulary/relators/auc': LocRelator.AUCTIONEER,
    'http://id.loc.gov/vocabulary/relators/sgn': LocRelator.SIGNER,
    'http://id.loc.gov/vocabulary/relators/ctt': LocRelator.CONTESTEE_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/pdr': LocRelator.PROJECT_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/cng': LocRelator.CINEMATOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/jud': LocRelator.JUDGE,
    'http://id.loc.gov/vocabulary/relators/led': LocRelator.LEAD,
    'http://id.loc.gov/vocabulary/relators/col': LocRelator.COLLECTOR,
    'http://id.loc.gov/vocabulary/relators/brd': LocRelator.BROADCASTER,
    'http://id.loc.gov/vocabulary/relators/own': LocRelator.OWNER,
    'http://id.loc.gov/vocabulary/relators/dfe': LocRelator.DEFENDANT_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/nrt': LocRelator.NARRATOR,
    'http://id.loc.gov/vocabulary/relators/cmt': LocRelator.COMPOSITOR,
    'http://id.loc.gov/vocabulary/relators/lit': LocRelator.LIBELANT_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/dnc': LocRelator.DANCER,
    'http://id.loc.gov/vocabulary/relators/etr': LocRelator.ETCHER,
    'http://id.loc.gov/vocabulary/relators/flm': LocRelator.FILM_EDITOR,
    'http://id.loc.gov/vocabulary/relators/lbt': LocRelator.LIBRETTIST,
    'http://id.loc.gov/vocabulary/relators/rpc': LocRelator.RADIO_PRODUCER,
    'http://id.loc.gov/vocabulary/relators/exp': LocRelator.EXPERT,
    'http://id.loc.gov/vocabulary/relators/rce': LocRelator.RECORDING_ENGINEER,
    'http://id.loc.gov/vocabulary/relators/sht': LocRelator.SUPPORTING_HOST,
    'http://id.loc.gov/vocabulary/relators/dte': LocRelator.DEDICATEE,
    'http://id.loc.gov/vocabulary/relators/rbr': LocRelator.RUBRICATOR,
    'http://id.loc.gov/vocabulary/relators/pra': LocRelator.PRAESES,
    'http://id.loc.gov/vocabulary/relators/cou': LocRelator.COURT_GOVERNED,
    'http://id.loc.gov/vocabulary/relators/coe': LocRelator.CONTESTANT_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/rpy': LocRelator.RESPONSIBLE_PARTY,
    'http://id.loc.gov/vocabulary/relators/aut': LocRelator.AUTHOR,
    'http://id.loc.gov/vocabulary/relators/mxe': LocRelator.MIXING_ENGINEER,
    'http://id.loc.gov/vocabulary/relators/itr': LocRelator.INSTRUMENTALIST,
    'http://id.loc.gov/vocabulary/relators/msd': LocRelator.MUSICAL_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/dgg':
      LocRelator.DEGREE_GRANTING_INSTITUTION,
    'http://id.loc.gov/vocabulary/relators/spn': LocRelator.SPONSOR,
    'http://id.loc.gov/vocabulary/relators/drt': LocRelator.DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/dbp': LocRelator.DISTRIBUTION_PLACE,
    'http://id.loc.gov/vocabulary/relators/jug':
      LocRelator.JURISDICTION_GOVERNED,
    'http://id.loc.gov/vocabulary/relators/djo': LocRelator.DJ,
    'http://id.loc.gov/vocabulary/relators/csp':
      LocRelator.CONSULTANT_TO_A_PROJECT,
    'http://id.loc.gov/vocabulary/relators/rst':
      LocRelator.RESPONDENT_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/bdd': LocRelator.BINDING_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/rdd': LocRelator.RADIO_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/cur': LocRelator.CURATOR,
    'http://id.loc.gov/vocabulary/relators/ths': LocRelator.THESIS_ADVISOR,
    'http://id.loc.gov/vocabulary/relators/edd': LocRelator.EDITORIAL_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/wac':
      LocRelator.WRITER_OF_ADDED_COMMENTARY,
    'http://id.loc.gov/vocabulary/relators/bkd': LocRelator.BOOK_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/mup': LocRelator.MUSIC_PROGRAMMER,
    'http://id.loc.gov/vocabulary/relators/len': LocRelator.LENDER,
    'http://id.loc.gov/vocabulary/relators/cpl': LocRelator.COMPLAINANT,
    'http://id.loc.gov/vocabulary/relators/sfx':
      LocRelator.SPECIAL_EFFECTS_PROVIDER,
    'http://id.loc.gov/vocabulary/relators/pad': LocRelator.PLACE_OF_ADDRESS,
    'http://id.loc.gov/vocabulary/relators/pfr': LocRelator.PROOFREADER,
    'http://id.loc.gov/vocabulary/relators/let': LocRelator.LIBELEE_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/cwt':
      LocRelator.COMMENTATOR_FOR_WRITTEN_TEXT,
    'http://id.loc.gov/vocabulary/relators/aft':
      LocRelator.AUTHOR_OF_AFTERWORD__COLOPHON__ETC_,
    'http://id.loc.gov/vocabulary/relators/clr': LocRelator.COLORIST,
    'http://id.loc.gov/vocabulary/relators/spy': LocRelator.SECOND_PARTY,
    'http://id.loc.gov/vocabulary/relators/dgs': LocRelator.DEGREE_SUPERVISOR,
    'http://id.loc.gov/vocabulary/relators/bnd': LocRelator.BINDER,
    'http://id.loc.gov/vocabulary/relators/lyr': LocRelator.LYRICIST,
    'http://id.loc.gov/vocabulary/relators/aqt':
      LocRelator.AUTHOR_IN_QUOTATIONS_OR_TEXT_ABSTRACTS,
    'http://id.loc.gov/vocabulary/relators/ren': LocRelator.RENDERER,
    'http://id.loc.gov/vocabulary/relators/mrk': LocRelator.MARKUP_EDITOR,
    'http://id.loc.gov/vocabulary/relators/dfd': LocRelator.DEFENDANT,
    'http://id.loc.gov/vocabulary/relators/prf': LocRelator.PERFORMER,
    'http://id.loc.gov/vocabulary/relators/ato': LocRelator.AUTOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/his': LocRelator.HOST_INSTITUTION,
    'http://id.loc.gov/vocabulary/relators/std': LocRelator.SET_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/fon': LocRelator.FOUNDER,
    'http://id.loc.gov/vocabulary/relators/dub': LocRelator.DUBIOUS_AUTHOR,
    'http://id.loc.gov/vocabulary/relators/pth': LocRelator.PATENT_HOLDER,
    'http://id.loc.gov/vocabulary/relators/tcd': LocRelator.TECHNICAL_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/inv': LocRelator.INVENTOR,
    'http://id.loc.gov/vocabulary/relators/tyg': LocRelator.TYPOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/asg': LocRelator.ASSIGNEE,
    'http://id.loc.gov/vocabulary/relators/wat':
      LocRelator.WRITER_OF_ADDED_TEXT,
    'http://id.loc.gov/vocabulary/relators/cop': LocRelator.CAMERA_OPERATOR,
    'http://id.loc.gov/vocabulary/relators/aus': LocRelator.SCREENWRITER,
    'http://id.loc.gov/vocabulary/relators/cmm': LocRelator.COMMENTATOR,
    'http://id.loc.gov/vocabulary/relators/ard': LocRelator.ARTISTIC_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/bsl': LocRelator.BOOKSELLER,
    'http://id.loc.gov/vocabulary/relators/edt': LocRelator.EDITOR,
    'http://id.loc.gov/vocabulary/relators/bkp': LocRelator.BOOK_PRODUCER,
    'http://id.loc.gov/vocabulary/relators/vdg': LocRelator.VIDEOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/cll': LocRelator.CALLIGRAPHER,
    'http://id.loc.gov/vocabulary/relators/ptt': LocRelator.PLAINTIFF_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/wdc': LocRelator.WOODCUTTER,
    'http://id.loc.gov/vocabulary/relators/rtm':
      LocRelator.RESEARCH_TEAM_MEMBER,
    'http://id.loc.gov/vocabulary/relators/ctg': LocRelator.CARTOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/eng': LocRelator.ENGINEER,
    'http://id.loc.gov/vocabulary/relators/mka': LocRelator.MAKEUP_ARTIST,
    'http://id.loc.gov/vocabulary/relators/res': LocRelator.RESEARCHER,
    'http://id.loc.gov/vocabulary/relators/ctr': LocRelator.CONTRACTOR,
    'http://id.loc.gov/vocabulary/relators/cad': LocRelator.CASTING_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/cov': LocRelator.COVER_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/frg': LocRelator.FORGER,
    'http://id.loc.gov/vocabulary/relators/trc': LocRelator.TRANSCRIBER,
    'http://id.loc.gov/vocabulary/relators/cpe':
      LocRelator.COMPLAINANT_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/tlg': LocRelator.TELEVISION_GUEST,
    'http://id.loc.gov/vocabulary/relators/pop': LocRelator.PRINTER_OF_PLATES,
    'http://id.loc.gov/vocabulary/relators/dbd': LocRelator.DUBBING_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/rps': LocRelator.REPOSITORY,
    'http://id.loc.gov/vocabulary/relators/lso': LocRelator.LICENSOR,
    'http://id.loc.gov/vocabulary/relators/fds': LocRelator.FILM_DISTRIBUTOR,
    'http://id.loc.gov/vocabulary/relators/red': LocRelator.REDAKTOR,
    'http://id.loc.gov/vocabulary/relators/dgc':
      LocRelator.DEGREE_COMMITTEE_MEMBER,
    'http://id.loc.gov/vocabulary/relators/ppt': LocRelator.PUPPETEER,
    'http://id.loc.gov/vocabulary/relators/str': LocRelator.STEREOTYPER,
    'http://id.loc.gov/vocabulary/relators/dft': LocRelator.DEFENDANT_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/crp': LocRelator.CORRESPONDENT,
    'http://id.loc.gov/vocabulary/relators/isb': LocRelator.ISSUING_BODY,
    'http://id.loc.gov/vocabulary/relators/rap': LocRelator.RAPPORTEUR,
    'http://id.loc.gov/vocabulary/relators/con': LocRelator.CONSERVATOR,
    'http://id.loc.gov/vocabulary/relators/wst':
      LocRelator.WRITER_OF_SUPPLEMENTARY_TEXTUAL_CONTENT,
    'http://id.loc.gov/vocabulary/relators/scr': LocRelator.SCRIBE,
    'http://id.loc.gov/vocabulary/relators/acp': LocRelator.ART_COPYIST,
    'http://id.loc.gov/vocabulary/relators/voc': LocRelator.VOCALIST,
    'http://id.loc.gov/vocabulary/relators/swd': LocRelator.SOFTWARE_DEVELOPER,
    'http://id.loc.gov/vocabulary/relators/lbr': LocRelator.LABORATORY,
    'http://id.loc.gov/vocabulary/relators/csl': LocRelator.CONSULTANT,
    'http://id.loc.gov/vocabulary/relators/sad': LocRelator.SCIENTIFIC_ADVISOR,
    'http://id.loc.gov/vocabulary/relators/dpt': LocRelator.DEPOSITOR,
    'http://id.loc.gov/vocabulary/relators/sds': LocRelator.SOUND_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/bjd': LocRelator.BOOKJACKET_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/edc':
      LocRelator.EDITOR_OF_COMPILATION,
    'http://id.loc.gov/vocabulary/relators/dpc': LocRelator.DEPICTED,
    'http://id.loc.gov/vocabulary/relators/fac': LocRelator.FACSIMILIST,
    'http://id.loc.gov/vocabulary/relators/scl': LocRelator.SCULPTOR,
    'http://id.loc.gov/vocabulary/relators/dst': LocRelator.DISTRIBUTOR,
    'http://id.loc.gov/vocabulary/relators/lie': LocRelator.LIBELANT_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/wft':
      LocRelator.WRITER_OF_INTERTITLES,
    'http://id.loc.gov/vocabulary/relators/cot':
      LocRelator.CONTESTANT_APPELLANT,
    'http://id.loc.gov/vocabulary/relators/prp': LocRelator.PRODUCTION_PLACE,
    'http://id.loc.gov/vocabulary/relators/sec': LocRelator.SECRETARY,
    'http://id.loc.gov/vocabulary/relators/fmp': LocRelator.FILM_PRODUCER,
    'http://id.loc.gov/vocabulary/relators/onp':
      LocRelator.ONSCREEN_PARTICIPANT,
    'http://id.loc.gov/vocabulary/relators/blw': LocRelator.BLURB_WRITER,
    'http://id.loc.gov/vocabulary/relators/wts':
      LocRelator.WRITER_OF_TELEVISION_STORY,
    'http://id.loc.gov/vocabulary/relators/cas': LocRelator.CASTER,
    'http://id.loc.gov/vocabulary/relators/prv': LocRelator.PROVIDER,
    'http://id.loc.gov/vocabulary/relators/pup': LocRelator.PUBLICATION_PLACE,
    'http://id.loc.gov/vocabulary/relators/lgd': LocRelator.LIGHTING_DESIGNER,
    'http://id.loc.gov/vocabulary/relators/oth': LocRelator.OTHER,
    'http://id.loc.gov/vocabulary/relators/plt': LocRelator.PLATEMAKER,
    'http://id.loc.gov/vocabulary/relators/mrb': LocRelator.MARBLER,
    'http://id.loc.gov/vocabulary/relators/cte': LocRelator.CONTESTEE_APPELLEE,
    'http://id.loc.gov/vocabulary/relators/fld': LocRelator.FIELD_DIRECTOR,
    'http://id.loc.gov/vocabulary/relators/wfs':
      LocRelator.WRITER_OF_FILM_STORY,
    'http://id.loc.gov/vocabulary/relators/opn': LocRelator.OPPONENT,
    'http://id.loc.gov/vocabulary/relators/anl': LocRelator.ANALYST,
    'http://id.loc.gov/vocabulary/relators/pma': LocRelator.PERMITTING_AGENCY,
    'http://id.loc.gov/vocabulary/relators/rxa': LocRelator.REMIX_ARTIST,
    'http://id.loc.gov/vocabulary/relators/pre': LocRelator.PRESENTER,
    'http://id.loc.gov/vocabulary/relators/pht': LocRelator.PHOTOGRAPHER,
    'http://id.loc.gov/vocabulary/relators/pta': LocRelator.PATENT_APPLICANT,
    'http://id.loc.gov/vocabulary/relators/dnr': LocRelator.DONOR,
    'http://id.loc.gov/vocabulary/relators/med': LocRelator.MEDIUM,
    'http://id.loc.gov/vocabulary/relators/evp': LocRelator.EVENT_PLACE,
    'http://id.loc.gov/vocabulary/relators/cnd': LocRelator.CONDUCTOR,
    'http://id.loc.gov/vocabulary/relators/gdv': LocRelator.GAME_DEVELOPER,
    'http://id.loc.gov/vocabulary/relators/dtm': LocRelator.DATA_MANAGER,
    'http://id.loc.gov/vocabulary/relators/ltr': LocRelator.LETTERER,
    'http://id.loc.gov/vocabulary/relators/ppm': LocRelator.PAPERMAKER,
    'http://id.loc.gov/vocabulary/relators/fpy': LocRelator.FIRST_PARTY,
    'http://id.loc.gov/vocabulary/relators/rsp': LocRelator.RESPONDENT,
    'http://id.loc.gov/vocabulary/relators/nan': LocRelator.NEWS_ANCHOR,
    'http://id.loc.gov/vocabulary/relators/crt': LocRelator.COURT_REPORTER,
    'http://id.loc.gov/vocabulary/relators/prd':
      LocRelator.PRODUCTION_PERSONNEL,
    'http://id.loc.gov/vocabulary/relators/fmk': LocRelator.FILMMAKER,
  }

  private static readonly relatorToLabelMap: Record<LocRelator, string> = {
    [LocRelator.FORMER_OWNER]: 'former owner',
    [LocRelator.AUDIO_ENGINEER]: 'audio engineer',
    [LocRelator.DESIGNER]: 'designer',
    [LocRelator.SPEAKER]: 'speaker',
    [LocRelator.BOOKPLATE_DESIGNER]: 'bookplate designer',
    [LocRelator.PRODUCTION_COMPANY]: 'production company',
    [LocRelator.DISSERTANT]: 'dissertant',
    [LocRelator.MUSICIAN]: 'musician',
    [LocRelator.COLLECTION_REGISTRAR]: 'collection registrar',
    [LocRelator.BOOK_ARTIST]: 'book artist',
    [LocRelator.RESPONDENT_APPELLEE]: 'respondent-appellee',
    [LocRelator.PLAINTIFF]: 'plaintiff',
    [LocRelator.ENGRAVER]: 'engraver',
    [LocRelator.CONCEPTOR]: 'conceptor',
    [LocRelator.GEOGRAPHIC_INFORMATION_SPECIALIST]:
      'geographic information specialist',
    [LocRelator.PRINTER]: 'printer',
    [LocRelator.APPLICANT]: 'applicant',
    [LocRelator.COPYRIGHT_CLAIMANT]: 'copyright claimant',
    [LocRelator.LIBELANT]: 'libelant',
    [LocRelator.APPELLEE]: 'appellee',
    [LocRelator.HONOREE]: 'honoree',
    [LocRelator.COMPLAINANT_APPELLANT]: 'complainant-appellant',
    [LocRelator.ORGANIZER]: 'organizer',
    [LocRelator.BRAILLE_EMBOSSER]: 'braille embosser',
    [LocRelator.ADAPTER]: 'adapter',
    [LocRelator.WRITER_OF_INTRODUCTION]: 'writer of introduction',
    [LocRelator.LITHOGRAPHER]: 'lithographer',
    [LocRelator.FUNDER]: 'funder',
    [LocRelator.CORRECTOR]: 'corrector',
    [LocRelator.VOICE_ACTOR]: 'voice actor',
    [LocRelator.WOOD_ENGRAVER]: 'wood engraver',
    [LocRelator.ANIMATOR]: 'animator',
    [LocRelator.MONITOR]: 'monitor',
    [LocRelator.ELECTROTYPER]: 'electrotyper',
    [LocRelator.ASSOCIATED_NAME]: 'associated name',
    [LocRelator.TELEVISION_PRODUCER]: 'television producer',
    [LocRelator.ORIGINATOR]: 'originator',
    [LocRelator.STAGE_DIRECTOR]: 'stage director',
    [LocRelator.COMPILER]: 'compiler',
    [LocRelator.INSCRIBER]: 'inscriber',
    [LocRelator.CREATOR]: 'creator',
    [LocRelator.MANUFACTURER]: 'manufacturer',
    [LocRelator.MODERATOR]: 'moderator',
    [LocRelator.FILM_DIRECTOR]: 'film director',
    [LocRelator.COMPOSER]: 'composer',
    [LocRelator.DATA_CONTRIBUTOR]: 'data contributor',
    [LocRelator.SCENARIST]: 'scenarist',
    [LocRelator.TYPE_DESIGNER]: 'type designer',
    [LocRelator.PRODUCER]: 'producer',
    [LocRelator.DELINEATOR]: 'delineator',
    [LocRelator.TECHNICAL_ADVISOR]: 'technical advisor',
    [LocRelator.CONTESTANT]: 'contestant',
    [LocRelator.CLIENT]: 'client',
    [LocRelator.PROCESS_CONTACT]: 'process contact',
    [LocRelator.TRANSLATOR]: 'translator',
    [LocRelator.PRODUCTION_MANAGER]: 'production manager',
    [LocRelator.MINUTE_TAKER]: 'minute taker',
    [LocRelator.PUBLISHER]: 'publisher',
    [LocRelator.ANNOTATOR]: 'annotator',
    [LocRelator.TELEVISION_WRITER]: 'television writer',
    [LocRelator.LIBELEE]: 'libelee',
    [LocRelator.AUDIO_PRODUCER]: 'audio producer',
    [LocRelator.ARRANGER]: 'arranger',
    [LocRelator.ENACTING_JURISDICTION]: 'enacting jurisdiction',
    [LocRelator.COSTUME_DESIGNER]: 'costume designer',
    [LocRelator.METAL_ENGRAVER]: 'metal engraver',
    [LocRelator.TELEVISION_DIRECTOR]: 'television director',
    [LocRelator.WRITER_OF_ADDED_LYRICS]: 'writer of added lyrics',
    [LocRelator.COPYRIGHT_HOLDER]: 'copyright holder',
    [LocRelator.CHOREOGRAPHER]: 'choreographer',
    [LocRelator.STORYTELLER]: 'storyteller',
    [LocRelator.METADATA_CONTACT]: 'metadata contact',
    [LocRelator.REVIEWER]: 'reviewer',
    [LocRelator.LICENSEE]: 'licensee',
    [LocRelator.COLLOTYPER]: 'collotyper',
    [LocRelator.INTERVIEWER]: 'interviewer',
    [LocRelator.ILLUSTRATOR]: 'illustrator',
    [LocRelator.ARCHITECT]: 'architect',
    [LocRelator.LIBELEE_APPELLEE]: 'libelee-appellee',
    [LocRelator.CONTESTEE]: 'contestee',
    [LocRelator.ART_DIRECTOR]: 'art director',
    [LocRelator.ELECTRICIAN]: 'electrician',
    [LocRelator.ONSCREEN_PRESENTER]: 'onscreen presenter',
    [LocRelator.BIBLIOGRAPHIC_ANTECEDENT]: 'bibliographic antecedent',
    [LocRelator.ADDRESSEE]: 'addressee',
    [LocRelator.ANNOUNCER]: 'announcer',
    [LocRelator.TELEVISION_HOST]: 'television host',
    [LocRelator.SOUND_ENGINEER]: 'sound engineer',
    [LocRelator.DRAFTSMAN]: 'draftsman',
    [LocRelator.STAGE_MANAGER]: 'stage manager',
    [LocRelator.ILLUMINATOR]: 'illuminator',
    [LocRelator.PUBLISHER_DIRECTOR]: 'publisher director',
    [LocRelator.ATTRIBUTED_NAME]: 'attributed name',
    [LocRelator.LABORATORY_DIRECTOR]: 'laboratory director',
    [LocRelator.PROGRAMMER]: 'programmer',
    [LocRelator.SINGER]: 'singer',
    [LocRelator.WRITER_OF_ACCOMPANYING_MATERIAL]:
      'writer of accompanying material',
    [LocRelator.SELLER]: 'seller',
    [LocRelator.RESTORATIONIST]: 'restorationist',
    [LocRelator.ABRIDGER]: 'abridger',
    [LocRelator.HOST]: 'host',
    [LocRelator.RESTAGER]: 'restager',
    [LocRelator.PRINTMAKER]: 'printmaker',
    [LocRelator.DEDICATOR]: 'dedicator',
    [LocRelator.RECORDIST]: 'recordist',
    [LocRelator.UNIVERSITY_PLACE]: 'university place',
    [LocRelator.RESEARCH_TEAM_HEAD]: 'research team head',
    [LocRelator.CONTRIBUTOR]: 'contributor',
    [LocRelator.PATRON]: 'patron',
    [LocRelator.SURVEYOR]: 'surveyor',
    [LocRelator.TEACHER]: 'teacher',
    [LocRelator.AUTHOR_OF_DIALOG]: 'author of dialog',
    [LocRelator.WRITER_OF_PREFACE]: 'writer of preface',
    [LocRelator.CENSOR]: 'censor',
    [LocRelator.PRODUCTION_DESIGNER]: 'production designer',
    [LocRelator.ARTIST]: 'artist',
    [LocRelator.MUSIC_COPYIST]: 'music copyist',
    [LocRelator.PANELIST]: 'panelist',
    [LocRelator.SETTING]: 'setting',
    [LocRelator.MANUFACTURE_PLACE]: 'manufacture place',
    [LocRelator.APPELLANT]: 'appellant',
    [LocRelator.PLAINTIFF_APPELLEE]: 'plaintiff-appellee',
    [LocRelator.EDITOR_OF_MOVING_IMAGE_WORK]: 'editor of moving image work',
    [LocRelator.WITNESS]: 'witness',
    [LocRelator.ACTOR]: 'actor',
    [LocRelator.REPORTER]: 'reporter',
    [LocRelator.STANDARDS_BODY]: 'standards body',
    [LocRelator.INTERVIEWEE]: 'interviewee',
    [LocRelator.VISUAL_EFFECTS_PROVIDER]: 'visual effects provider',
    [LocRelator.AUTHOR_OF_INTRODUCTION__ETC_]: 'author of introduction, etc.',
    [LocRelator.LANDSCAPE_ARCHITECT]: 'landscape architect',
    [LocRelator.AUCTIONEER]: 'auctioneer',
    [LocRelator.SIGNER]: 'signer',
    [LocRelator.CONTESTEE_APPELLANT]: 'contestee-appellant',
    [LocRelator.PROJECT_DIRECTOR]: 'project director',
    [LocRelator.CINEMATOGRAPHER]: 'cinematographer',
    [LocRelator.JUDGE]: 'judge',
    [LocRelator.LEAD]: 'lead',
    [LocRelator.COLLECTOR]: 'collector',
    [LocRelator.BROADCASTER]: 'broadcaster',
    [LocRelator.OWNER]: 'owner',
    [LocRelator.DEFENDANT_APPELLEE]: 'defendant-appellee',
    [LocRelator.NARRATOR]: 'narrator',
    [LocRelator.COMPOSITOR]: 'compositor',
    [LocRelator.LIBELANT_APPELLANT]: 'libelant-appellant',
    [LocRelator.DANCER]: 'dancer',
    [LocRelator.ETCHER]: 'etcher',
    [LocRelator.FILM_EDITOR]: 'film editor',
    [LocRelator.LIBRETTIST]: 'librettist',
    [LocRelator.RADIO_PRODUCER]: 'radio producer',
    [LocRelator.EXPERT]: 'expert',
    [LocRelator.RECORDING_ENGINEER]: 'recording engineer',
    [LocRelator.SUPPORTING_HOST]: 'supporting host',
    [LocRelator.DEDICATEE]: 'dedicatee',
    [LocRelator.RUBRICATOR]: 'rubricator',
    [LocRelator.PRAESES]: 'praeses',
    [LocRelator.COURT_GOVERNED]: 'court governed',
    [LocRelator.CONTESTANT_APPELLEE]: 'contestant-appellee',
    [LocRelator.RESPONSIBLE_PARTY]: 'responsible party',
    [LocRelator.AUTHOR]: 'author',
    [LocRelator.MIXING_ENGINEER]: 'mixing engineer',
    [LocRelator.INSTRUMENTALIST]: 'instrumentalist',
    [LocRelator.MUSICAL_DIRECTOR]: 'musical director',
    [LocRelator.DEGREE_GRANTING_INSTITUTION]: 'degree granting institution',
    [LocRelator.SPONSOR]: 'sponsor',
    [LocRelator.DIRECTOR]: 'director',
    [LocRelator.DISTRIBUTION_PLACE]: 'distribution place',
    [LocRelator.JURISDICTION_GOVERNED]: 'jurisdiction governed',
    [LocRelator.DJ]: 'dj',
    [LocRelator.CONSULTANT_TO_A_PROJECT]: 'consultant to a project',
    [LocRelator.RESPONDENT_APPELLANT]: 'respondent-appellant',
    [LocRelator.BINDING_DESIGNER]: 'binding designer',
    [LocRelator.RADIO_DIRECTOR]: 'radio director',
    [LocRelator.CURATOR]: 'curator',
    [LocRelator.THESIS_ADVISOR]: 'thesis advisor',
    [LocRelator.EDITORIAL_DIRECTOR]: 'editorial director',
    [LocRelator.WRITER_OF_ADDED_COMMENTARY]: 'writer of added commentary',
    [LocRelator.BOOK_DESIGNER]: 'book designer',
    [LocRelator.MUSIC_PROGRAMMER]: 'music programmer',
    [LocRelator.LENDER]: 'lender',
    [LocRelator.COMPLAINANT]: 'complainant',
    [LocRelator.SPECIAL_EFFECTS_PROVIDER]: 'special effects provider',
    [LocRelator.PLACE_OF_ADDRESS]: 'place of address',
    [LocRelator.PROOFREADER]: 'proofreader',
    [LocRelator.LIBELEE_APPELLANT]: 'libelee-appellant',
    [LocRelator.COMMENTATOR_FOR_WRITTEN_TEXT]: 'commentator for written text',
    [LocRelator.AUTHOR_OF_AFTERWORD__COLOPHON__ETC_]:
      'author of afterword, colophon, etc.',
    [LocRelator.COLORIST]: 'colorist',
    [LocRelator.SECOND_PARTY]: 'second party',
    [LocRelator.DEGREE_SUPERVISOR]: 'degree supervisor',
    [LocRelator.BINDER]: 'binder',
    [LocRelator.LYRICIST]: 'lyricist',
    [LocRelator.AUTHOR_IN_QUOTATIONS_OR_TEXT_ABSTRACTS]:
      'author in quotations or text abstracts',
    [LocRelator.RENDERER]: 'renderer',
    [LocRelator.MARKUP_EDITOR]: 'markup editor',
    [LocRelator.DEFENDANT]: 'defendant',
    [LocRelator.PERFORMER]: 'performer',
    [LocRelator.AUTOGRAPHER]: 'autographer',
    [LocRelator.HOST_INSTITUTION]: 'host institution',
    [LocRelator.SET_DESIGNER]: 'set designer',
    [LocRelator.FOUNDER]: 'founder',
    [LocRelator.DUBIOUS_AUTHOR]: 'dubious author',
    [LocRelator.PATENT_HOLDER]: 'patent holder',
    [LocRelator.TECHNICAL_DIRECTOR]: 'technical director',
    [LocRelator.INVENTOR]: 'inventor',
    [LocRelator.TYPOGRAPHER]: 'typographer',
    [LocRelator.ASSIGNEE]: 'assignee',
    [LocRelator.WRITER_OF_ADDED_TEXT]: 'writer of added text',
    [LocRelator.CAMERA_OPERATOR]: 'camera operator',
    [LocRelator.SCREENWRITER]: 'screenwriter',
    [LocRelator.COMMENTATOR]: 'commentator',
    [LocRelator.ARTISTIC_DIRECTOR]: 'artistic director',
    [LocRelator.BOOKSELLER]: 'bookseller',
    [LocRelator.EDITOR]: 'editor',
    [LocRelator.BOOK_PRODUCER]: 'book producer',
    [LocRelator.VIDEOGRAPHER]: 'videographer',
    [LocRelator.CALLIGRAPHER]: 'calligrapher',
    [LocRelator.PLAINTIFF_APPELLANT]: 'plaintiff-appellant',
    [LocRelator.WOODCUTTER]: 'woodcutter',
    [LocRelator.RESEARCH_TEAM_MEMBER]: 'research team member',
    [LocRelator.CARTOGRAPHER]: 'cartographer',
    [LocRelator.ENGINEER]: 'engineer',
    [LocRelator.MAKEUP_ARTIST]: 'makeup artist',
    [LocRelator.RESEARCHER]: 'researcher',
    [LocRelator.CONTRACTOR]: 'contractor',
    [LocRelator.CASTING_DIRECTOR]: 'casting director',
    [LocRelator.COVER_DESIGNER]: 'cover designer',
    [LocRelator.FORGER]: 'forger',
    [LocRelator.TRANSCRIBER]: 'transcriber',
    [LocRelator.COMPLAINANT_APPELLEE]: 'complainant-appellee',
    [LocRelator.TELEVISION_GUEST]: 'television guest',
    [LocRelator.PRINTER_OF_PLATES]: 'printer of plates',
    [LocRelator.DUBBING_DIRECTOR]: 'dubbing director',
    [LocRelator.REPOSITORY]: 'repository',
    [LocRelator.LICENSOR]: 'licensor',
    [LocRelator.FILM_DISTRIBUTOR]: 'film distributor',
    [LocRelator.REDAKTOR]: 'redaktor',
    [LocRelator.DEGREE_COMMITTEE_MEMBER]: 'degree committee member',
    [LocRelator.PUPPETEER]: 'puppeteer',
    [LocRelator.STEREOTYPER]: 'stereotyper',
    [LocRelator.DEFENDANT_APPELLANT]: 'defendant-appellant',
    [LocRelator.CORRESPONDENT]: 'correspondent',
    [LocRelator.ISSUING_BODY]: 'issuing body',
    [LocRelator.RAPPORTEUR]: 'rapporteur',
    [LocRelator.CONSERVATOR]: 'conservator',
    [LocRelator.WRITER_OF_SUPPLEMENTARY_TEXTUAL_CONTENT]:
      'writer of supplementary textual content',
    [LocRelator.SCRIBE]: 'scribe',
    [LocRelator.ART_COPYIST]: 'art copyist',
    [LocRelator.VOCALIST]: 'vocalist',
    [LocRelator.SOFTWARE_DEVELOPER]: 'software developer',
    [LocRelator.LABORATORY]: 'laboratory',
    [LocRelator.CONSULTANT]: 'consultant',
    [LocRelator.SCIENTIFIC_ADVISOR]: 'scientific advisor',
    [LocRelator.DEPOSITOR]: 'depositor',
    [LocRelator.SOUND_DESIGNER]: 'sound designer',
    [LocRelator.BOOKJACKET_DESIGNER]: 'bookjacket designer',
    [LocRelator.EDITOR_OF_COMPILATION]: 'editor of compilation',
    [LocRelator.DEPICTED]: 'depicted',
    [LocRelator.FACSIMILIST]: 'facsimilist',
    [LocRelator.SCULPTOR]: 'sculptor',
    [LocRelator.DISTRIBUTOR]: 'distributor',
    [LocRelator.LIBELANT_APPELLEE]: 'libelant-appellee',
    [LocRelator.WRITER_OF_INTERTITLES]: 'writer of intertitles',
    [LocRelator.CONTESTANT_APPELLANT]: 'contestant-appellant',
    [LocRelator.PRODUCTION_PLACE]: 'production place',
    [LocRelator.SECRETARY]: 'secretary',
    [LocRelator.FILM_PRODUCER]: 'film producer',
    [LocRelator.ONSCREEN_PARTICIPANT]: 'onscreen participant',
    [LocRelator.BLURB_WRITER]: 'blurb writer',
    [LocRelator.WRITER_OF_TELEVISION_STORY]: 'writer of television story',
    [LocRelator.CASTER]: 'caster',
    [LocRelator.PROVIDER]: 'provider',
    [LocRelator.PUBLICATION_PLACE]: 'publication place',
    [LocRelator.LIGHTING_DESIGNER]: 'lighting designer',
    [LocRelator.OTHER]: 'other',
    [LocRelator.PLATEMAKER]: 'platemaker',
    [LocRelator.MARBLER]: 'marbler',
    [LocRelator.CONTESTEE_APPELLEE]: 'contestee-appellee',
    [LocRelator.FIELD_DIRECTOR]: 'field director',
    [LocRelator.WRITER_OF_FILM_STORY]: 'writer of film story',
    [LocRelator.OPPONENT]: 'opponent',
    [LocRelator.ANALYST]: 'analyst',
    [LocRelator.PERMITTING_AGENCY]: 'permitting agency',
    [LocRelator.REMIX_ARTIST]: 'remix artist',
    [LocRelator.PRESENTER]: 'presenter',
    [LocRelator.PHOTOGRAPHER]: 'photographer',
    [LocRelator.PATENT_APPLICANT]: 'patent applicant',
    [LocRelator.DONOR]: 'donor',
    [LocRelator.MEDIUM]: 'medium',
    [LocRelator.EVENT_PLACE]: 'event place',
    [LocRelator.CONDUCTOR]: 'conductor',
    [LocRelator.GAME_DEVELOPER]: 'game developer',
    [LocRelator.DATA_MANAGER]: 'data manager',
    [LocRelator.LETTERER]: 'letterer',
    [LocRelator.PAPERMAKER]: 'papermaker',
    [LocRelator.FIRST_PARTY]: 'first party',
    [LocRelator.RESPONDENT]: 'respondent',
    [LocRelator.NEWS_ANCHOR]: 'news anchor',
    [LocRelator.COURT_REPORTER]: 'court reporter',
    [LocRelator.PRODUCTION_PERSONNEL]: 'production personnel',
    [LocRelator.FILMMAKER]: 'filmmaker',
  }

  private static readonly labelToRelatorMap: Record<string, LocRelator> = {
    'former owner': LocRelator.FORMER_OWNER,
    'audio engineer': LocRelator.AUDIO_ENGINEER,
    designer: LocRelator.DESIGNER,
    speaker: LocRelator.SPEAKER,
    'bookplate designer': LocRelator.BOOKPLATE_DESIGNER,
    'production company': LocRelator.PRODUCTION_COMPANY,
    dissertant: LocRelator.DISSERTANT,
    musician: LocRelator.MUSICIAN,
    'collection registrar': LocRelator.COLLECTION_REGISTRAR,
    'book artist': LocRelator.BOOK_ARTIST,
    'respondent-appellee': LocRelator.RESPONDENT_APPELLEE,
    plaintiff: LocRelator.PLAINTIFF,
    engraver: LocRelator.ENGRAVER,
    conceptor: LocRelator.CONCEPTOR,
    'geographic information specialist':
      LocRelator.GEOGRAPHIC_INFORMATION_SPECIALIST,
    printer: LocRelator.PRINTER,
    applicant: LocRelator.APPLICANT,
    'copyright claimant': LocRelator.COPYRIGHT_CLAIMANT,
    libelant: LocRelator.LIBELANT,
    appellee: LocRelator.APPELLEE,
    honoree: LocRelator.HONOREE,
    'complainant-appellant': LocRelator.COMPLAINANT_APPELLANT,
    organizer: LocRelator.ORGANIZER,
    'braille embosser': LocRelator.BRAILLE_EMBOSSER,
    adapter: LocRelator.ADAPTER,
    'writer of introduction': LocRelator.WRITER_OF_INTRODUCTION,
    lithographer: LocRelator.LITHOGRAPHER,
    funder: LocRelator.FUNDER,
    corrector: LocRelator.CORRECTOR,
    'voice actor': LocRelator.VOICE_ACTOR,
    'wood engraver': LocRelator.WOOD_ENGRAVER,
    animator: LocRelator.ANIMATOR,
    monitor: LocRelator.MONITOR,
    electrotyper: LocRelator.ELECTROTYPER,
    'associated name': LocRelator.ASSOCIATED_NAME,
    'television producer': LocRelator.TELEVISION_PRODUCER,
    originator: LocRelator.ORIGINATOR,
    'stage director': LocRelator.STAGE_DIRECTOR,
    compiler: LocRelator.COMPILER,
    inscriber: LocRelator.INSCRIBER,
    creator: LocRelator.CREATOR,
    manufacturer: LocRelator.MANUFACTURER,
    moderator: LocRelator.MODERATOR,
    'film director': LocRelator.FILM_DIRECTOR,
    composer: LocRelator.COMPOSER,
    'data contributor': LocRelator.DATA_CONTRIBUTOR,
    scenarist: LocRelator.SCENARIST,
    'type designer': LocRelator.TYPE_DESIGNER,
    producer: LocRelator.PRODUCER,
    delineator: LocRelator.DELINEATOR,
    'technical advisor': LocRelator.TECHNICAL_ADVISOR,
    contestant: LocRelator.CONTESTANT,
    client: LocRelator.CLIENT,
    'process contact': LocRelator.PROCESS_CONTACT,
    translator: LocRelator.TRANSLATOR,
    'production manager': LocRelator.PRODUCTION_MANAGER,
    'minute taker': LocRelator.MINUTE_TAKER,
    publisher: LocRelator.PUBLISHER,
    annotator: LocRelator.ANNOTATOR,
    'television writer': LocRelator.TELEVISION_WRITER,
    libelee: LocRelator.LIBELEE,
    'audio producer': LocRelator.AUDIO_PRODUCER,
    arranger: LocRelator.ARRANGER,
    'enacting jurisdiction': LocRelator.ENACTING_JURISDICTION,
    'costume designer': LocRelator.COSTUME_DESIGNER,
    'metal engraver': LocRelator.METAL_ENGRAVER,
    'television director': LocRelator.TELEVISION_DIRECTOR,
    'writer of added lyrics': LocRelator.WRITER_OF_ADDED_LYRICS,
    'copyright holder': LocRelator.COPYRIGHT_HOLDER,
    choreographer: LocRelator.CHOREOGRAPHER,
    storyteller: LocRelator.STORYTELLER,
    'metadata contact': LocRelator.METADATA_CONTACT,
    reviewer: LocRelator.REVIEWER,
    licensee: LocRelator.LICENSEE,
    collotyper: LocRelator.COLLOTYPER,
    interviewer: LocRelator.INTERVIEWER,
    illustrator: LocRelator.ILLUSTRATOR,
    architect: LocRelator.ARCHITECT,
    'libelee-appellee': LocRelator.LIBELEE_APPELLEE,
    contestee: LocRelator.CONTESTEE,
    'art director': LocRelator.ART_DIRECTOR,
    electrician: LocRelator.ELECTRICIAN,
    'onscreen presenter': LocRelator.ONSCREEN_PRESENTER,
    'bibliographic antecedent': LocRelator.BIBLIOGRAPHIC_ANTECEDENT,
    addressee: LocRelator.ADDRESSEE,
    announcer: LocRelator.ANNOUNCER,
    'television host': LocRelator.TELEVISION_HOST,
    'sound engineer': LocRelator.SOUND_ENGINEER,
    draftsman: LocRelator.DRAFTSMAN,
    'stage manager': LocRelator.STAGE_MANAGER,
    illuminator: LocRelator.ILLUMINATOR,
    'publisher director': LocRelator.PUBLISHER_DIRECTOR,
    'attributed name': LocRelator.ATTRIBUTED_NAME,
    'laboratory director': LocRelator.LABORATORY_DIRECTOR,
    programmer: LocRelator.PROGRAMMER,
    singer: LocRelator.SINGER,
    'writer of accompanying material':
      LocRelator.WRITER_OF_ACCOMPANYING_MATERIAL,
    seller: LocRelator.SELLER,
    restorationist: LocRelator.RESTORATIONIST,
    abridger: LocRelator.ABRIDGER,
    host: LocRelator.HOST,
    restager: LocRelator.RESTAGER,
    printmaker: LocRelator.PRINTMAKER,
    dedicator: LocRelator.DEDICATOR,
    recordist: LocRelator.RECORDIST,
    'university place': LocRelator.UNIVERSITY_PLACE,
    'research team head': LocRelator.RESEARCH_TEAM_HEAD,
    contributor: LocRelator.CONTRIBUTOR,
    patron: LocRelator.PATRON,
    surveyor: LocRelator.SURVEYOR,
    teacher: LocRelator.TEACHER,
    'author of dialog': LocRelator.AUTHOR_OF_DIALOG,
    'writer of preface': LocRelator.WRITER_OF_PREFACE,
    censor: LocRelator.CENSOR,
    'production designer': LocRelator.PRODUCTION_DESIGNER,
    artist: LocRelator.ARTIST,
    'music copyist': LocRelator.MUSIC_COPYIST,
    panelist: LocRelator.PANELIST,
    setting: LocRelator.SETTING,
    'manufacture place': LocRelator.MANUFACTURE_PLACE,
    appellant: LocRelator.APPELLANT,
    'plaintiff-appellee': LocRelator.PLAINTIFF_APPELLEE,
    'editor of moving image work': LocRelator.EDITOR_OF_MOVING_IMAGE_WORK,
    witness: LocRelator.WITNESS,
    actor: LocRelator.ACTOR,
    reporter: LocRelator.REPORTER,
    'standards body': LocRelator.STANDARDS_BODY,
    interviewee: LocRelator.INTERVIEWEE,
    'visual effects provider': LocRelator.VISUAL_EFFECTS_PROVIDER,
    'author of introduction, etc.': LocRelator.AUTHOR_OF_INTRODUCTION__ETC_,
    'landscape architect': LocRelator.LANDSCAPE_ARCHITECT,
    auctioneer: LocRelator.AUCTIONEER,
    signer: LocRelator.SIGNER,
    'contestee-appellant': LocRelator.CONTESTEE_APPELLANT,
    'project director': LocRelator.PROJECT_DIRECTOR,
    cinematographer: LocRelator.CINEMATOGRAPHER,
    judge: LocRelator.JUDGE,
    lead: LocRelator.LEAD,
    collector: LocRelator.COLLECTOR,
    broadcaster: LocRelator.BROADCASTER,
    owner: LocRelator.OWNER,
    'defendant-appellee': LocRelator.DEFENDANT_APPELLEE,
    narrator: LocRelator.NARRATOR,
    compositor: LocRelator.COMPOSITOR,
    'libelant-appellant': LocRelator.LIBELANT_APPELLANT,
    dancer: LocRelator.DANCER,
    etcher: LocRelator.ETCHER,
    'film editor': LocRelator.FILM_EDITOR,
    librettist: LocRelator.LIBRETTIST,
    'radio producer': LocRelator.RADIO_PRODUCER,
    expert: LocRelator.EXPERT,
    'recording engineer': LocRelator.RECORDING_ENGINEER,
    'supporting host': LocRelator.SUPPORTING_HOST,
    dedicatee: LocRelator.DEDICATEE,
    rubricator: LocRelator.RUBRICATOR,
    praeses: LocRelator.PRAESES,
    'court governed': LocRelator.COURT_GOVERNED,
    'contestant-appellee': LocRelator.CONTESTANT_APPELLEE,
    'responsible party': LocRelator.RESPONSIBLE_PARTY,
    author: LocRelator.AUTHOR,
    'mixing engineer': LocRelator.MIXING_ENGINEER,
    instrumentalist: LocRelator.INSTRUMENTALIST,
    'musical director': LocRelator.MUSICAL_DIRECTOR,
    'degree granting institution': LocRelator.DEGREE_GRANTING_INSTITUTION,
    sponsor: LocRelator.SPONSOR,
    director: LocRelator.DIRECTOR,
    'distribution place': LocRelator.DISTRIBUTION_PLACE,
    'jurisdiction governed': LocRelator.JURISDICTION_GOVERNED,
    dj: LocRelator.DJ,
    'consultant to a project': LocRelator.CONSULTANT_TO_A_PROJECT,
    'respondent-appellant': LocRelator.RESPONDENT_APPELLANT,
    'binding designer': LocRelator.BINDING_DESIGNER,
    'radio director': LocRelator.RADIO_DIRECTOR,
    curator: LocRelator.CURATOR,
    'thesis advisor': LocRelator.THESIS_ADVISOR,
    'editorial director': LocRelator.EDITORIAL_DIRECTOR,
    'writer of added commentary': LocRelator.WRITER_OF_ADDED_COMMENTARY,
    'book designer': LocRelator.BOOK_DESIGNER,
    'music programmer': LocRelator.MUSIC_PROGRAMMER,
    lender: LocRelator.LENDER,
    complainant: LocRelator.COMPLAINANT,
    'special effects provider': LocRelator.SPECIAL_EFFECTS_PROVIDER,
    'place of address': LocRelator.PLACE_OF_ADDRESS,
    proofreader: LocRelator.PROOFREADER,
    'libelee-appellant': LocRelator.LIBELEE_APPELLANT,
    'commentator for written text': LocRelator.COMMENTATOR_FOR_WRITTEN_TEXT,
    'author of afterword, colophon, etc.':
      LocRelator.AUTHOR_OF_AFTERWORD__COLOPHON__ETC_,
    colorist: LocRelator.COLORIST,
    'second party': LocRelator.SECOND_PARTY,
    'degree supervisor': LocRelator.DEGREE_SUPERVISOR,
    binder: LocRelator.BINDER,
    lyricist: LocRelator.LYRICIST,
    'author in quotations or text abstracts':
      LocRelator.AUTHOR_IN_QUOTATIONS_OR_TEXT_ABSTRACTS,
    renderer: LocRelator.RENDERER,
    'markup editor': LocRelator.MARKUP_EDITOR,
    defendant: LocRelator.DEFENDANT,
    performer: LocRelator.PERFORMER,
    autographer: LocRelator.AUTOGRAPHER,
    'host institution': LocRelator.HOST_INSTITUTION,
    'set designer': LocRelator.SET_DESIGNER,
    founder: LocRelator.FOUNDER,
    'dubious author': LocRelator.DUBIOUS_AUTHOR,
    'patent holder': LocRelator.PATENT_HOLDER,
    'technical director': LocRelator.TECHNICAL_DIRECTOR,
    inventor: LocRelator.INVENTOR,
    typographer: LocRelator.TYPOGRAPHER,
    assignee: LocRelator.ASSIGNEE,
    'writer of added text': LocRelator.WRITER_OF_ADDED_TEXT,
    'camera operator': LocRelator.CAMERA_OPERATOR,
    screenwriter: LocRelator.SCREENWRITER,
    commentator: LocRelator.COMMENTATOR,
    'artistic director': LocRelator.ARTISTIC_DIRECTOR,
    bookseller: LocRelator.BOOKSELLER,
    editor: LocRelator.EDITOR,
    'book producer': LocRelator.BOOK_PRODUCER,
    videographer: LocRelator.VIDEOGRAPHER,
    calligrapher: LocRelator.CALLIGRAPHER,
    'plaintiff-appellant': LocRelator.PLAINTIFF_APPELLANT,
    woodcutter: LocRelator.WOODCUTTER,
    'research team member': LocRelator.RESEARCH_TEAM_MEMBER,
    cartographer: LocRelator.CARTOGRAPHER,
    engineer: LocRelator.ENGINEER,
    'makeup artist': LocRelator.MAKEUP_ARTIST,
    researcher: LocRelator.RESEARCHER,
    contractor: LocRelator.CONTRACTOR,
    'casting director': LocRelator.CASTING_DIRECTOR,
    'cover designer': LocRelator.COVER_DESIGNER,
    forger: LocRelator.FORGER,
    transcriber: LocRelator.TRANSCRIBER,
    'complainant-appellee': LocRelator.COMPLAINANT_APPELLEE,
    'television guest': LocRelator.TELEVISION_GUEST,
    'printer of plates': LocRelator.PRINTER_OF_PLATES,
    'dubbing director': LocRelator.DUBBING_DIRECTOR,
    repository: LocRelator.REPOSITORY,
    licensor: LocRelator.LICENSOR,
    'film distributor': LocRelator.FILM_DISTRIBUTOR,
    redaktor: LocRelator.REDAKTOR,
    'degree committee member': LocRelator.DEGREE_COMMITTEE_MEMBER,
    puppeteer: LocRelator.PUPPETEER,
    stereotyper: LocRelator.STEREOTYPER,
    'defendant-appellant': LocRelator.DEFENDANT_APPELLANT,
    correspondent: LocRelator.CORRESPONDENT,
    'issuing body': LocRelator.ISSUING_BODY,
    rapporteur: LocRelator.RAPPORTEUR,
    conservator: LocRelator.CONSERVATOR,
    'writer of supplementary textual content':
      LocRelator.WRITER_OF_SUPPLEMENTARY_TEXTUAL_CONTENT,
    scribe: LocRelator.SCRIBE,
    'art copyist': LocRelator.ART_COPYIST,
    vocalist: LocRelator.VOCALIST,
    'software developer': LocRelator.SOFTWARE_DEVELOPER,
    laboratory: LocRelator.LABORATORY,
    consultant: LocRelator.CONSULTANT,
    'scientific advisor': LocRelator.SCIENTIFIC_ADVISOR,
    depositor: LocRelator.DEPOSITOR,
    'sound designer': LocRelator.SOUND_DESIGNER,
    'bookjacket designer': LocRelator.BOOKJACKET_DESIGNER,
    'editor of compilation': LocRelator.EDITOR_OF_COMPILATION,
    depicted: LocRelator.DEPICTED,
    facsimilist: LocRelator.FACSIMILIST,
    sculptor: LocRelator.SCULPTOR,
    distributor: LocRelator.DISTRIBUTOR,
    'libelant-appellee': LocRelator.LIBELANT_APPELLEE,
    'writer of intertitles': LocRelator.WRITER_OF_INTERTITLES,
    'contestant-appellant': LocRelator.CONTESTANT_APPELLANT,
    'production place': LocRelator.PRODUCTION_PLACE,
    secretary: LocRelator.SECRETARY,
    'film producer': LocRelator.FILM_PRODUCER,
    'onscreen participant': LocRelator.ONSCREEN_PARTICIPANT,
    'blurb writer': LocRelator.BLURB_WRITER,
    'writer of television story': LocRelator.WRITER_OF_TELEVISION_STORY,
    caster: LocRelator.CASTER,
    provider: LocRelator.PROVIDER,
    'publication place': LocRelator.PUBLICATION_PLACE,
    'lighting designer': LocRelator.LIGHTING_DESIGNER,
    other: LocRelator.OTHER,
    platemaker: LocRelator.PLATEMAKER,
    marbler: LocRelator.MARBLER,
    'contestee-appellee': LocRelator.CONTESTEE_APPELLEE,
    'field director': LocRelator.FIELD_DIRECTOR,
    'writer of film story': LocRelator.WRITER_OF_FILM_STORY,
    opponent: LocRelator.OPPONENT,
    analyst: LocRelator.ANALYST,
    'permitting agency': LocRelator.PERMITTING_AGENCY,
    'remix artist': LocRelator.REMIX_ARTIST,
    presenter: LocRelator.PRESENTER,
    photographer: LocRelator.PHOTOGRAPHER,
    'patent applicant': LocRelator.PATENT_APPLICANT,
    donor: LocRelator.DONOR,
    medium: LocRelator.MEDIUM,
    'event place': LocRelator.EVENT_PLACE,
    conductor: LocRelator.CONDUCTOR,
    'game developer': LocRelator.GAME_DEVELOPER,
    'data manager': LocRelator.DATA_MANAGER,
    letterer: LocRelator.LETTERER,
    papermaker: LocRelator.PAPERMAKER,
    'first party': LocRelator.FIRST_PARTY,
    respondent: LocRelator.RESPONDENT,
    'news anchor': LocRelator.NEWS_ANCHOR,
    'court reporter': LocRelator.COURT_REPORTER,
    'production personnel': LocRelator.PRODUCTION_PERSONNEL,
    filmmaker: LocRelator.FILMMAKER,
  }

  private static readonly relatorToUriMap: Record<LocRelator, string> = {
    [LocRelator.FORMER_OWNER]: 'http://id.loc.gov/vocabulary/relators/fmo',
    [LocRelator.AUDIO_ENGINEER]: 'http://id.loc.gov/vocabulary/relators/aue',
    [LocRelator.DESIGNER]: 'http://id.loc.gov/vocabulary/relators/dsr',
    [LocRelator.SPEAKER]: 'http://id.loc.gov/vocabulary/relators/spk',
    [LocRelator.BOOKPLATE_DESIGNER]:
      'http://id.loc.gov/vocabulary/relators/bpd',
    [LocRelator.PRODUCTION_COMPANY]:
      'http://id.loc.gov/vocabulary/relators/prn',
    [LocRelator.DISSERTANT]: 'http://id.loc.gov/vocabulary/relators/dis',
    [LocRelator.MUSICIAN]: 'http://id.loc.gov/vocabulary/relators/mus',
    [LocRelator.COLLECTION_REGISTRAR]:
      'http://id.loc.gov/vocabulary/relators/cor',
    [LocRelator.BOOK_ARTIST]: 'http://id.loc.gov/vocabulary/relators/bka',
    [LocRelator.RESPONDENT_APPELLEE]:
      'http://id.loc.gov/vocabulary/relators/rse',
    [LocRelator.PLAINTIFF]: 'http://id.loc.gov/vocabulary/relators/ptf',
    [LocRelator.ENGRAVER]: 'http://id.loc.gov/vocabulary/relators/egr',
    [LocRelator.CONCEPTOR]: 'http://id.loc.gov/vocabulary/relators/ccp',
    [LocRelator.GEOGRAPHIC_INFORMATION_SPECIALIST]:
      'http://id.loc.gov/vocabulary/relators/gis',
    [LocRelator.PRINTER]: 'http://id.loc.gov/vocabulary/relators/prt',
    [LocRelator.APPLICANT]: 'http://id.loc.gov/vocabulary/relators/app',
    [LocRelator.COPYRIGHT_CLAIMANT]:
      'http://id.loc.gov/vocabulary/relators/cpc',
    [LocRelator.LIBELANT]: 'http://id.loc.gov/vocabulary/relators/lil',
    [LocRelator.APPELLEE]: 'http://id.loc.gov/vocabulary/relators/ape',
    [LocRelator.HONOREE]: 'http://id.loc.gov/vocabulary/relators/hnr',
    [LocRelator.COMPLAINANT_APPELLANT]:
      'http://id.loc.gov/vocabulary/relators/cpt',
    [LocRelator.ORGANIZER]: 'http://id.loc.gov/vocabulary/relators/orm',
    [LocRelator.BRAILLE_EMBOSSER]: 'http://id.loc.gov/vocabulary/relators/brl',
    [LocRelator.ADAPTER]: 'http://id.loc.gov/vocabulary/relators/adp',
    [LocRelator.WRITER_OF_INTRODUCTION]:
      'http://id.loc.gov/vocabulary/relators/win',
    [LocRelator.LITHOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/ltg',
    [LocRelator.FUNDER]: 'http://id.loc.gov/vocabulary/relators/fnd',
    [LocRelator.CORRECTOR]: 'http://id.loc.gov/vocabulary/relators/crr',
    [LocRelator.VOICE_ACTOR]: 'http://id.loc.gov/vocabulary/relators/vac',
    [LocRelator.WOOD_ENGRAVER]: 'http://id.loc.gov/vocabulary/relators/wde',
    [LocRelator.ANIMATOR]: 'http://id.loc.gov/vocabulary/relators/anm',
    [LocRelator.MONITOR]: 'http://id.loc.gov/vocabulary/relators/mon',
    [LocRelator.ELECTROTYPER]: 'http://id.loc.gov/vocabulary/relators/elt',
    [LocRelator.ASSOCIATED_NAME]: 'http://id.loc.gov/vocabulary/relators/asn',
    [LocRelator.TELEVISION_PRODUCER]:
      'http://id.loc.gov/vocabulary/relators/tlp',
    [LocRelator.ORIGINATOR]: 'http://id.loc.gov/vocabulary/relators/org',
    [LocRelator.STAGE_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/sgd',
    [LocRelator.COMPILER]: 'http://id.loc.gov/vocabulary/relators/com',
    [LocRelator.INSCRIBER]: 'http://id.loc.gov/vocabulary/relators/ins',
    [LocRelator.CREATOR]: 'http://id.loc.gov/vocabulary/relators/cre',
    [LocRelator.MANUFACTURER]: 'http://id.loc.gov/vocabulary/relators/mfr',
    [LocRelator.MODERATOR]: 'http://id.loc.gov/vocabulary/relators/mod',
    [LocRelator.FILM_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/fmd',
    [LocRelator.COMPOSER]: 'http://id.loc.gov/vocabulary/relators/cmp',
    [LocRelator.DATA_CONTRIBUTOR]: 'http://id.loc.gov/vocabulary/relators/dtc',
    [LocRelator.SCENARIST]: 'http://id.loc.gov/vocabulary/relators/sce',
    [LocRelator.TYPE_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/tyd',
    [LocRelator.PRODUCER]: 'http://id.loc.gov/vocabulary/relators/pro',
    [LocRelator.DELINEATOR]: 'http://id.loc.gov/vocabulary/relators/dln',
    [LocRelator.TECHNICAL_ADVISOR]: 'http://id.loc.gov/vocabulary/relators/tad',
    [LocRelator.CONTESTANT]: 'http://id.loc.gov/vocabulary/relators/cos',
    [LocRelator.CLIENT]: 'http://id.loc.gov/vocabulary/relators/cli',
    [LocRelator.PROCESS_CONTACT]: 'http://id.loc.gov/vocabulary/relators/prc',
    [LocRelator.TRANSLATOR]: 'http://id.loc.gov/vocabulary/relators/trl',
    [LocRelator.PRODUCTION_MANAGER]:
      'http://id.loc.gov/vocabulary/relators/pmn',
    [LocRelator.MINUTE_TAKER]: 'http://id.loc.gov/vocabulary/relators/mtk',
    [LocRelator.PUBLISHER]: 'http://id.loc.gov/vocabulary/relators/pbl',
    [LocRelator.ANNOTATOR]: 'http://id.loc.gov/vocabulary/relators/ann',
    [LocRelator.TELEVISION_WRITER]: 'http://id.loc.gov/vocabulary/relators/tau',
    [LocRelator.LIBELEE]: 'http://id.loc.gov/vocabulary/relators/lel',
    [LocRelator.AUDIO_PRODUCER]: 'http://id.loc.gov/vocabulary/relators/aup',
    [LocRelator.ARRANGER]: 'http://id.loc.gov/vocabulary/relators/arr',
    [LocRelator.ENACTING_JURISDICTION]:
      'http://id.loc.gov/vocabulary/relators/enj',
    [LocRelator.COSTUME_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/cst',
    [LocRelator.METAL_ENGRAVER]: 'http://id.loc.gov/vocabulary/relators/mte',
    [LocRelator.TELEVISION_DIRECTOR]:
      'http://id.loc.gov/vocabulary/relators/tld',
    [LocRelator.WRITER_OF_ADDED_LYRICS]:
      'http://id.loc.gov/vocabulary/relators/wal',
    [LocRelator.COPYRIGHT_HOLDER]: 'http://id.loc.gov/vocabulary/relators/cph',
    [LocRelator.CHOREOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/chr',
    [LocRelator.STORYTELLER]: 'http://id.loc.gov/vocabulary/relators/stl',
    [LocRelator.METADATA_CONTACT]: 'http://id.loc.gov/vocabulary/relators/mdc',
    [LocRelator.REVIEWER]: 'http://id.loc.gov/vocabulary/relators/rev',
    [LocRelator.LICENSEE]: 'http://id.loc.gov/vocabulary/relators/lse',
    [LocRelator.COLLOTYPER]: 'http://id.loc.gov/vocabulary/relators/clt',
    [LocRelator.INTERVIEWER]: 'http://id.loc.gov/vocabulary/relators/ivr',
    [LocRelator.ILLUSTRATOR]: 'http://id.loc.gov/vocabulary/relators/ill',
    [LocRelator.ARCHITECT]: 'http://id.loc.gov/vocabulary/relators/arc',
    [LocRelator.LIBELEE_APPELLEE]: 'http://id.loc.gov/vocabulary/relators/lee',
    [LocRelator.CONTESTEE]: 'http://id.loc.gov/vocabulary/relators/cts',
    [LocRelator.ART_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/adi',
    [LocRelator.ELECTRICIAN]: 'http://id.loc.gov/vocabulary/relators/elg',
    [LocRelator.ONSCREEN_PRESENTER]:
      'http://id.loc.gov/vocabulary/relators/osp',
    [LocRelator.BIBLIOGRAPHIC_ANTECEDENT]:
      'http://id.loc.gov/vocabulary/relators/ant',
    [LocRelator.ADDRESSEE]: 'http://id.loc.gov/vocabulary/relators/rcp',
    [LocRelator.ANNOUNCER]: 'http://id.loc.gov/vocabulary/relators/anc',
    [LocRelator.TELEVISION_HOST]: 'http://id.loc.gov/vocabulary/relators/tlh',
    [LocRelator.SOUND_ENGINEER]: 'http://id.loc.gov/vocabulary/relators/sde',
    [LocRelator.DRAFTSMAN]: 'http://id.loc.gov/vocabulary/relators/drm',
    [LocRelator.STAGE_MANAGER]: 'http://id.loc.gov/vocabulary/relators/stm',
    [LocRelator.ILLUMINATOR]: 'http://id.loc.gov/vocabulary/relators/ilu',
    [LocRelator.PUBLISHER_DIRECTOR]:
      'http://id.loc.gov/vocabulary/relators/pbd',
    [LocRelator.ATTRIBUTED_NAME]: 'http://id.loc.gov/vocabulary/relators/att',
    [LocRelator.LABORATORY_DIRECTOR]:
      'http://id.loc.gov/vocabulary/relators/ldr',
    [LocRelator.PROGRAMMER]: 'http://id.loc.gov/vocabulary/relators/prg',
    [LocRelator.SINGER]: 'http://id.loc.gov/vocabulary/relators/sng',
    [LocRelator.WRITER_OF_ACCOMPANYING_MATERIAL]:
      'http://id.loc.gov/vocabulary/relators/wam',
    [LocRelator.SELLER]: 'http://id.loc.gov/vocabulary/relators/sll',
    [LocRelator.RESTORATIONIST]: 'http://id.loc.gov/vocabulary/relators/rsr',
    [LocRelator.ABRIDGER]: 'http://id.loc.gov/vocabulary/relators/abr',
    [LocRelator.HOST]: 'http://id.loc.gov/vocabulary/relators/hst',
    [LocRelator.RESTAGER]: 'http://id.loc.gov/vocabulary/relators/rsg',
    [LocRelator.PRINTMAKER]: 'http://id.loc.gov/vocabulary/relators/prm',
    [LocRelator.DEDICATOR]: 'http://id.loc.gov/vocabulary/relators/dto',
    [LocRelator.RECORDIST]: 'http://id.loc.gov/vocabulary/relators/rcd',
    [LocRelator.UNIVERSITY_PLACE]: 'http://id.loc.gov/vocabulary/relators/uvp',
    [LocRelator.RESEARCH_TEAM_HEAD]:
      'http://id.loc.gov/vocabulary/relators/rth',
    [LocRelator.CONTRIBUTOR]: 'http://id.loc.gov/vocabulary/relators/ctb',
    [LocRelator.PATRON]: 'http://id.loc.gov/vocabulary/relators/pat',
    [LocRelator.SURVEYOR]: 'http://id.loc.gov/vocabulary/relators/srv',
    [LocRelator.TEACHER]: 'http://id.loc.gov/vocabulary/relators/tch',
    [LocRelator.AUTHOR_OF_DIALOG]: 'http://id.loc.gov/vocabulary/relators/aud',
    [LocRelator.WRITER_OF_PREFACE]: 'http://id.loc.gov/vocabulary/relators/wpr',
    [LocRelator.CENSOR]: 'http://id.loc.gov/vocabulary/relators/cns',
    [LocRelator.PRODUCTION_DESIGNER]:
      'http://id.loc.gov/vocabulary/relators/prs',
    [LocRelator.ARTIST]: 'http://id.loc.gov/vocabulary/relators/art',
    [LocRelator.MUSIC_COPYIST]: 'http://id.loc.gov/vocabulary/relators/mcp',
    [LocRelator.PANELIST]: 'http://id.loc.gov/vocabulary/relators/pan',
    [LocRelator.SETTING]: 'http://id.loc.gov/vocabulary/relators/stg',
    [LocRelator.MANUFACTURE_PLACE]: 'http://id.loc.gov/vocabulary/relators/mfp',
    [LocRelator.APPELLANT]: 'http://id.loc.gov/vocabulary/relators/apl',
    [LocRelator.PLAINTIFF_APPELLEE]:
      'http://id.loc.gov/vocabulary/relators/pte',
    [LocRelator.EDITOR_OF_MOVING_IMAGE_WORK]:
      'http://id.loc.gov/vocabulary/relators/edm',
    [LocRelator.WITNESS]: 'http://id.loc.gov/vocabulary/relators/wit',
    [LocRelator.ACTOR]: 'http://id.loc.gov/vocabulary/relators/act',
    [LocRelator.REPORTER]: 'http://id.loc.gov/vocabulary/relators/rpt',
    [LocRelator.STANDARDS_BODY]: 'http://id.loc.gov/vocabulary/relators/stn',
    [LocRelator.INTERVIEWEE]: 'http://id.loc.gov/vocabulary/relators/ive',
    [LocRelator.VISUAL_EFFECTS_PROVIDER]:
      'http://id.loc.gov/vocabulary/relators/vfx',
    [LocRelator.AUTHOR_OF_INTRODUCTION__ETC_]:
      'http://id.loc.gov/vocabulary/relators/aui',
    [LocRelator.LANDSCAPE_ARCHITECT]:
      'http://id.loc.gov/vocabulary/relators/lsa',
    [LocRelator.AUCTIONEER]: 'http://id.loc.gov/vocabulary/relators/auc',
    [LocRelator.SIGNER]: 'http://id.loc.gov/vocabulary/relators/sgn',
    [LocRelator.CONTESTEE_APPELLANT]:
      'http://id.loc.gov/vocabulary/relators/ctt',
    [LocRelator.PROJECT_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/pdr',
    [LocRelator.CINEMATOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/cng',
    [LocRelator.JUDGE]: 'http://id.loc.gov/vocabulary/relators/jud',
    [LocRelator.LEAD]: 'http://id.loc.gov/vocabulary/relators/led',
    [LocRelator.COLLECTOR]: 'http://id.loc.gov/vocabulary/relators/col',
    [LocRelator.BROADCASTER]: 'http://id.loc.gov/vocabulary/relators/brd',
    [LocRelator.OWNER]: 'http://id.loc.gov/vocabulary/relators/own',
    [LocRelator.DEFENDANT_APPELLEE]:
      'http://id.loc.gov/vocabulary/relators/dfe',
    [LocRelator.NARRATOR]: 'http://id.loc.gov/vocabulary/relators/nrt',
    [LocRelator.COMPOSITOR]: 'http://id.loc.gov/vocabulary/relators/cmt',
    [LocRelator.LIBELANT_APPELLANT]:
      'http://id.loc.gov/vocabulary/relators/lit',
    [LocRelator.DANCER]: 'http://id.loc.gov/vocabulary/relators/dnc',
    [LocRelator.ETCHER]: 'http://id.loc.gov/vocabulary/relators/etr',
    [LocRelator.FILM_EDITOR]: 'http://id.loc.gov/vocabulary/relators/flm',
    [LocRelator.LIBRETTIST]: 'http://id.loc.gov/vocabulary/relators/lbt',
    [LocRelator.RADIO_PRODUCER]: 'http://id.loc.gov/vocabulary/relators/rpc',
    [LocRelator.EXPERT]: 'http://id.loc.gov/vocabulary/relators/exp',
    [LocRelator.RECORDING_ENGINEER]:
      'http://id.loc.gov/vocabulary/relators/rce',
    [LocRelator.SUPPORTING_HOST]: 'http://id.loc.gov/vocabulary/relators/sht',
    [LocRelator.DEDICATEE]: 'http://id.loc.gov/vocabulary/relators/dte',
    [LocRelator.RUBRICATOR]: 'http://id.loc.gov/vocabulary/relators/rbr',
    [LocRelator.PRAESES]: 'http://id.loc.gov/vocabulary/relators/pra',
    [LocRelator.COURT_GOVERNED]: 'http://id.loc.gov/vocabulary/relators/cou',
    [LocRelator.CONTESTANT_APPELLEE]:
      'http://id.loc.gov/vocabulary/relators/coe',
    [LocRelator.RESPONSIBLE_PARTY]: 'http://id.loc.gov/vocabulary/relators/rpy',
    [LocRelator.AUTHOR]: 'http://id.loc.gov/vocabulary/relators/aut',
    [LocRelator.MIXING_ENGINEER]: 'http://id.loc.gov/vocabulary/relators/mxe',
    [LocRelator.INSTRUMENTALIST]: 'http://id.loc.gov/vocabulary/relators/itr',
    [LocRelator.MUSICAL_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/msd',
    [LocRelator.DEGREE_GRANTING_INSTITUTION]:
      'http://id.loc.gov/vocabulary/relators/dgg',
    [LocRelator.SPONSOR]: 'http://id.loc.gov/vocabulary/relators/spn',
    [LocRelator.DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/drt',
    [LocRelator.DISTRIBUTION_PLACE]:
      'http://id.loc.gov/vocabulary/relators/dbp',
    [LocRelator.JURISDICTION_GOVERNED]:
      'http://id.loc.gov/vocabulary/relators/jug',
    [LocRelator.DJ]: 'http://id.loc.gov/vocabulary/relators/djo',
    [LocRelator.CONSULTANT_TO_A_PROJECT]:
      'http://id.loc.gov/vocabulary/relators/csp',
    [LocRelator.RESPONDENT_APPELLANT]:
      'http://id.loc.gov/vocabulary/relators/rst',
    [LocRelator.BINDING_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/bdd',
    [LocRelator.RADIO_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/rdd',
    [LocRelator.CURATOR]: 'http://id.loc.gov/vocabulary/relators/cur',
    [LocRelator.THESIS_ADVISOR]: 'http://id.loc.gov/vocabulary/relators/ths',
    [LocRelator.EDITORIAL_DIRECTOR]:
      'http://id.loc.gov/vocabulary/relators/edd',
    [LocRelator.WRITER_OF_ADDED_COMMENTARY]:
      'http://id.loc.gov/vocabulary/relators/wac',
    [LocRelator.BOOK_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/bkd',
    [LocRelator.MUSIC_PROGRAMMER]: 'http://id.loc.gov/vocabulary/relators/mup',
    [LocRelator.LENDER]: 'http://id.loc.gov/vocabulary/relators/len',
    [LocRelator.COMPLAINANT]: 'http://id.loc.gov/vocabulary/relators/cpl',
    [LocRelator.SPECIAL_EFFECTS_PROVIDER]:
      'http://id.loc.gov/vocabulary/relators/sfx',
    [LocRelator.PLACE_OF_ADDRESS]: 'http://id.loc.gov/vocabulary/relators/pad',
    [LocRelator.PROOFREADER]: 'http://id.loc.gov/vocabulary/relators/pfr',
    [LocRelator.LIBELEE_APPELLANT]: 'http://id.loc.gov/vocabulary/relators/let',
    [LocRelator.COMMENTATOR_FOR_WRITTEN_TEXT]:
      'http://id.loc.gov/vocabulary/relators/cwt',
    [LocRelator.AUTHOR_OF_AFTERWORD__COLOPHON__ETC_]:
      'http://id.loc.gov/vocabulary/relators/aft',
    [LocRelator.COLORIST]: 'http://id.loc.gov/vocabulary/relators/clr',
    [LocRelator.SECOND_PARTY]: 'http://id.loc.gov/vocabulary/relators/spy',
    [LocRelator.DEGREE_SUPERVISOR]: 'http://id.loc.gov/vocabulary/relators/dgs',
    [LocRelator.BINDER]: 'http://id.loc.gov/vocabulary/relators/bnd',
    [LocRelator.LYRICIST]: 'http://id.loc.gov/vocabulary/relators/lyr',
    [LocRelator.AUTHOR_IN_QUOTATIONS_OR_TEXT_ABSTRACTS]:
      'http://id.loc.gov/vocabulary/relators/aqt',
    [LocRelator.RENDERER]: 'http://id.loc.gov/vocabulary/relators/ren',
    [LocRelator.MARKUP_EDITOR]: 'http://id.loc.gov/vocabulary/relators/mrk',
    [LocRelator.DEFENDANT]: 'http://id.loc.gov/vocabulary/relators/dfd',
    [LocRelator.PERFORMER]: 'http://id.loc.gov/vocabulary/relators/prf',
    [LocRelator.AUTOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/ato',
    [LocRelator.HOST_INSTITUTION]: 'http://id.loc.gov/vocabulary/relators/his',
    [LocRelator.SET_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/std',
    [LocRelator.FOUNDER]: 'http://id.loc.gov/vocabulary/relators/fon',
    [LocRelator.DUBIOUS_AUTHOR]: 'http://id.loc.gov/vocabulary/relators/dub',
    [LocRelator.PATENT_HOLDER]: 'http://id.loc.gov/vocabulary/relators/pth',
    [LocRelator.TECHNICAL_DIRECTOR]:
      'http://id.loc.gov/vocabulary/relators/tcd',
    [LocRelator.INVENTOR]: 'http://id.loc.gov/vocabulary/relators/inv',
    [LocRelator.TYPOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/tyg',
    [LocRelator.ASSIGNEE]: 'http://id.loc.gov/vocabulary/relators/asg',
    [LocRelator.WRITER_OF_ADDED_TEXT]:
      'http://id.loc.gov/vocabulary/relators/wat',
    [LocRelator.CAMERA_OPERATOR]: 'http://id.loc.gov/vocabulary/relators/cop',
    [LocRelator.SCREENWRITER]: 'http://id.loc.gov/vocabulary/relators/aus',
    [LocRelator.COMMENTATOR]: 'http://id.loc.gov/vocabulary/relators/cmm',
    [LocRelator.ARTISTIC_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/ard',
    [LocRelator.BOOKSELLER]: 'http://id.loc.gov/vocabulary/relators/bsl',
    [LocRelator.EDITOR]: 'http://id.loc.gov/vocabulary/relators/edt',
    [LocRelator.BOOK_PRODUCER]: 'http://id.loc.gov/vocabulary/relators/bkp',
    [LocRelator.VIDEOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/vdg',
    [LocRelator.CALLIGRAPHER]: 'http://id.loc.gov/vocabulary/relators/cll',
    [LocRelator.PLAINTIFF_APPELLANT]:
      'http://id.loc.gov/vocabulary/relators/ptt',
    [LocRelator.WOODCUTTER]: 'http://id.loc.gov/vocabulary/relators/wdc',
    [LocRelator.RESEARCH_TEAM_MEMBER]:
      'http://id.loc.gov/vocabulary/relators/rtm',
    [LocRelator.CARTOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/ctg',
    [LocRelator.ENGINEER]: 'http://id.loc.gov/vocabulary/relators/eng',
    [LocRelator.MAKEUP_ARTIST]: 'http://id.loc.gov/vocabulary/relators/mka',
    [LocRelator.RESEARCHER]: 'http://id.loc.gov/vocabulary/relators/res',
    [LocRelator.CONTRACTOR]: 'http://id.loc.gov/vocabulary/relators/ctr',
    [LocRelator.CASTING_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/cad',
    [LocRelator.COVER_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/cov',
    [LocRelator.FORGER]: 'http://id.loc.gov/vocabulary/relators/frg',
    [LocRelator.TRANSCRIBER]: 'http://id.loc.gov/vocabulary/relators/trc',
    [LocRelator.COMPLAINANT_APPELLEE]:
      'http://id.loc.gov/vocabulary/relators/cpe',
    [LocRelator.TELEVISION_GUEST]: 'http://id.loc.gov/vocabulary/relators/tlg',
    [LocRelator.PRINTER_OF_PLATES]: 'http://id.loc.gov/vocabulary/relators/pop',
    [LocRelator.DUBBING_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/dbd',
    [LocRelator.REPOSITORY]: 'http://id.loc.gov/vocabulary/relators/rps',
    [LocRelator.LICENSOR]: 'http://id.loc.gov/vocabulary/relators/lso',
    [LocRelator.FILM_DISTRIBUTOR]: 'http://id.loc.gov/vocabulary/relators/fds',
    [LocRelator.REDAKTOR]: 'http://id.loc.gov/vocabulary/relators/red',
    [LocRelator.DEGREE_COMMITTEE_MEMBER]:
      'http://id.loc.gov/vocabulary/relators/dgc',
    [LocRelator.PUPPETEER]: 'http://id.loc.gov/vocabulary/relators/ppt',
    [LocRelator.STEREOTYPER]: 'http://id.loc.gov/vocabulary/relators/str',
    [LocRelator.DEFENDANT_APPELLANT]:
      'http://id.loc.gov/vocabulary/relators/dft',
    [LocRelator.CORRESPONDENT]: 'http://id.loc.gov/vocabulary/relators/crp',
    [LocRelator.ISSUING_BODY]: 'http://id.loc.gov/vocabulary/relators/isb',
    [LocRelator.RAPPORTEUR]: 'http://id.loc.gov/vocabulary/relators/rap',
    [LocRelator.CONSERVATOR]: 'http://id.loc.gov/vocabulary/relators/con',
    [LocRelator.WRITER_OF_SUPPLEMENTARY_TEXTUAL_CONTENT]:
      'http://id.loc.gov/vocabulary/relators/wst',
    [LocRelator.SCRIBE]: 'http://id.loc.gov/vocabulary/relators/scr',
    [LocRelator.ART_COPYIST]: 'http://id.loc.gov/vocabulary/relators/acp',
    [LocRelator.VOCALIST]: 'http://id.loc.gov/vocabulary/relators/voc',
    [LocRelator.SOFTWARE_DEVELOPER]:
      'http://id.loc.gov/vocabulary/relators/swd',
    [LocRelator.LABORATORY]: 'http://id.loc.gov/vocabulary/relators/lbr',
    [LocRelator.CONSULTANT]: 'http://id.loc.gov/vocabulary/relators/csl',
    [LocRelator.SCIENTIFIC_ADVISOR]:
      'http://id.loc.gov/vocabulary/relators/sad',
    [LocRelator.DEPOSITOR]: 'http://id.loc.gov/vocabulary/relators/dpt',
    [LocRelator.SOUND_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/sds',
    [LocRelator.BOOKJACKET_DESIGNER]:
      'http://id.loc.gov/vocabulary/relators/bjd',
    [LocRelator.EDITOR_OF_COMPILATION]:
      'http://id.loc.gov/vocabulary/relators/edc',
    [LocRelator.DEPICTED]: 'http://id.loc.gov/vocabulary/relators/dpc',
    [LocRelator.FACSIMILIST]: 'http://id.loc.gov/vocabulary/relators/fac',
    [LocRelator.SCULPTOR]: 'http://id.loc.gov/vocabulary/relators/scl',
    [LocRelator.DISTRIBUTOR]: 'http://id.loc.gov/vocabulary/relators/dst',
    [LocRelator.LIBELANT_APPELLEE]: 'http://id.loc.gov/vocabulary/relators/lie',
    [LocRelator.WRITER_OF_INTERTITLES]:
      'http://id.loc.gov/vocabulary/relators/wft',
    [LocRelator.CONTESTANT_APPELLANT]:
      'http://id.loc.gov/vocabulary/relators/cot',
    [LocRelator.PRODUCTION_PLACE]: 'http://id.loc.gov/vocabulary/relators/prp',
    [LocRelator.SECRETARY]: 'http://id.loc.gov/vocabulary/relators/sec',
    [LocRelator.FILM_PRODUCER]: 'http://id.loc.gov/vocabulary/relators/fmp',
    [LocRelator.ONSCREEN_PARTICIPANT]:
      'http://id.loc.gov/vocabulary/relators/onp',
    [LocRelator.BLURB_WRITER]: 'http://id.loc.gov/vocabulary/relators/blw',
    [LocRelator.WRITER_OF_TELEVISION_STORY]:
      'http://id.loc.gov/vocabulary/relators/wts',
    [LocRelator.CASTER]: 'http://id.loc.gov/vocabulary/relators/cas',
    [LocRelator.PROVIDER]: 'http://id.loc.gov/vocabulary/relators/prv',
    [LocRelator.PUBLICATION_PLACE]: 'http://id.loc.gov/vocabulary/relators/pup',
    [LocRelator.LIGHTING_DESIGNER]: 'http://id.loc.gov/vocabulary/relators/lgd',
    [LocRelator.OTHER]: 'http://id.loc.gov/vocabulary/relators/oth',
    [LocRelator.PLATEMAKER]: 'http://id.loc.gov/vocabulary/relators/plt',
    [LocRelator.MARBLER]: 'http://id.loc.gov/vocabulary/relators/mrb',
    [LocRelator.CONTESTEE_APPELLEE]:
      'http://id.loc.gov/vocabulary/relators/cte',
    [LocRelator.FIELD_DIRECTOR]: 'http://id.loc.gov/vocabulary/relators/fld',
    [LocRelator.WRITER_OF_FILM_STORY]:
      'http://id.loc.gov/vocabulary/relators/wfs',
    [LocRelator.OPPONENT]: 'http://id.loc.gov/vocabulary/relators/opn',
    [LocRelator.ANALYST]: 'http://id.loc.gov/vocabulary/relators/anl',
    [LocRelator.PERMITTING_AGENCY]: 'http://id.loc.gov/vocabulary/relators/pma',
    [LocRelator.REMIX_ARTIST]: 'http://id.loc.gov/vocabulary/relators/rxa',
    [LocRelator.PRESENTER]: 'http://id.loc.gov/vocabulary/relators/pre',
    [LocRelator.PHOTOGRAPHER]: 'http://id.loc.gov/vocabulary/relators/pht',
    [LocRelator.PATENT_APPLICANT]: 'http://id.loc.gov/vocabulary/relators/pta',
    [LocRelator.DONOR]: 'http://id.loc.gov/vocabulary/relators/dnr',
    [LocRelator.MEDIUM]: 'http://id.loc.gov/vocabulary/relators/med',
    [LocRelator.EVENT_PLACE]: 'http://id.loc.gov/vocabulary/relators/evp',
    [LocRelator.CONDUCTOR]: 'http://id.loc.gov/vocabulary/relators/cnd',
    [LocRelator.GAME_DEVELOPER]: 'http://id.loc.gov/vocabulary/relators/gdv',
    [LocRelator.DATA_MANAGER]: 'http://id.loc.gov/vocabulary/relators/dtm',
    [LocRelator.LETTERER]: 'http://id.loc.gov/vocabulary/relators/ltr',
    [LocRelator.PAPERMAKER]: 'http://id.loc.gov/vocabulary/relators/ppm',
    [LocRelator.FIRST_PARTY]: 'http://id.loc.gov/vocabulary/relators/fpy',
    [LocRelator.RESPONDENT]: 'http://id.loc.gov/vocabulary/relators/rsp',
    [LocRelator.NEWS_ANCHOR]: 'http://id.loc.gov/vocabulary/relators/nan',
    [LocRelator.COURT_REPORTER]: 'http://id.loc.gov/vocabulary/relators/crt',
    [LocRelator.PRODUCTION_PERSONNEL]:
      'http://id.loc.gov/vocabulary/relators/prd',
    [LocRelator.FILMMAKER]: 'http://id.loc.gov/vocabulary/relators/fmk',
  }

  static fromURI(uri: string): LocRelator | null {
    return Object.prototype.hasOwnProperty.call(
      LocRelatorHelper.uriToRelatorMap,
      uri,
    )
      ? LocRelatorHelper.uriToRelatorMap[uri]
      : null
  }

  static toLabel(relator: LocRelator): string {
    return LocRelatorHelper.relatorToLabelMap[relator] || relator
  }

  static fromLabel(label: string): LocRelator | null {
    return LocRelatorHelper.labelToRelatorMap[label] || null
  }

  static toUri(relator: LocRelator): string | null {
    return LocRelatorHelper.relatorToUriMap[relator] || null
  }

  static convertValue(value: string) {
    switch (value) {
      case 'AUTHOR_OF_INTRODUCTION':
        return 'AUTHOR_OF_INTRODUCTION__ETC_'
      case 'AUTHOR_OF_AFTERWORD':
      case 'AUTHOR_OF_COLOPHON':
        return 'AUTHOR_OF_AFTERWORD__COLOPHON__ETC_'
      default:
        return value
    }
  }

  static getRelatorFromKey(value: string) {
    const convertedValue = LocRelatorHelper.convertValue(value)
    if (convertedValue in LocRelator) {
      return LocRelator[convertedValue as keyof typeof LocRelator]
    } else {
      return null
    }
  }
}
