import { defineMessage } from '@lingui/core/macro'
import { MessageDescriptor } from '@lingui/core'
import { SourceRecordType } from '@prisma/client'

export const SourceRecordTypeLabels: Record<
  SourceRecordType,
  MessageDescriptor
> = {
  [SourceRecordType.Article]: defineMessage`sources_page_article_icon_label`,
  [SourceRecordType.AudiovisualDocument]: defineMessage`sources_page_audiovisual_document_icon_label`,
  [SourceRecordType.Book]: defineMessage`sources_page_book_icon_label`,
  [SourceRecordType.Chapter]: defineMessage`sources_page_chapter_icon_label`,
  [SourceRecordType.Document]: defineMessage`sources_page_document_icon_label`,
  [SourceRecordType.Excerpt]: defineMessage`sources_page_excerpt_icon_label`,
  [SourceRecordType.Letter]: defineMessage`sources_page_letter_icon_label`,
  [SourceRecordType.Manual]: defineMessage`sources_page_manual_icon_label`,
  [SourceRecordType.Map]: defineMessage`sources_page_map_icon_label`,
  [SourceRecordType.Note]: defineMessage`sources_page_note_icon_label`,
  [SourceRecordType.Patent]: defineMessage`sources_page_patent_icon_label`,
  [SourceRecordType.Proceedings]: defineMessage`sources_page_proceedings_icon_label`,
  [SourceRecordType.Standard]: defineMessage`sources_page_standard_icon_label`,
  [SourceRecordType.Thesis]: defineMessage`sources_page_thesis_icon_label`,
  [SourceRecordType.BlogPost]: defineMessage`sources_page_blog_post_icon_label`,
  [SourceRecordType.ConferenceOutput]: defineMessage`sources_page_conference_output_icon_label`,
  [SourceRecordType.DataPaper]: defineMessage`sources_page_data_paper_icon_label`,
  [SourceRecordType.Lecture]: defineMessage`sources_page_lecture_icon_label`,
  [SourceRecordType.MasterThesis]: defineMessage`sources_page_master_thesis_icon_label`,
  [SourceRecordType.Other]: defineMessage`sources_page_other_icon_label`,
  [SourceRecordType.PeerReview]: defineMessage`sources_page_peer_review_icon_label`,
  [SourceRecordType.Report]: defineMessage`sources_page_report_icon_label`,
  [SourceRecordType.ResearchReport]: defineMessage`sources_page_research_report_icon_label`,
  [SourceRecordType.Software]: defineMessage`sources_page_software_icon_label`,
  [SourceRecordType.TechnicalReport]: defineMessage`sources_page_technical_report_icon_label`,
  [SourceRecordType.BookReview]: defineMessage`sources_page_book_review_icon_label`,
  [SourceRecordType.ConferencePaper]: defineMessage`sources_page_conference_paper_icon_label`,
  [SourceRecordType.ConferencePoster]: defineMessage`sources_page_conference_poster_icon_label`,
  [SourceRecordType.DataManagementPlan]: defineMessage`sources_page_data_management_plan_icon_label`,
  [SourceRecordType.Dataset]: defineMessage`sources_page_dataset_icon_label`,
  [SourceRecordType.Editorial]: defineMessage`sources_page_editorial_icon_label`,
  [SourceRecordType.Erratum]: defineMessage`sources_page_erratum_icon_label`,
  [SourceRecordType.Image]: defineMessage`sources_page_image_icon_label`,
  [SourceRecordType.MetadataDocument]: defineMessage`sources_page_metadata_document_icon_label`,
  [SourceRecordType.Preprint]: defineMessage`sources_page_preprint_icon_label`,
  [SourceRecordType.ReferenceBook]: defineMessage`sources_page_reference_book_icon_label`,
  [SourceRecordType.ReviewArticle]: defineMessage`sources_page_review_article_icon_label`,
  [SourceRecordType.ReviewPaper]: defineMessage`sources_page_review_paper_icon_label`,
  [SourceRecordType.StillImage]: defineMessage`sources_page_still_image_icon_label`,
  [SourceRecordType.WorkingPaper]: defineMessage`sources_page_working_paper_icon_label`,
  [SourceRecordType.Grant]: defineMessage`sources_page_grant_icon_label`,
  [SourceRecordType.Work]: defineMessage`sources_page_work_icon_label`,
  [SourceRecordType.Unknown]: defineMessage`sources_page_unknown_icon_label`,
}
