version: '3.8'

services:
  svp-db:
    image: postgres:16
    container_name: svp-db
    restart: always
    environment:
      POSTGRES_USER: sovisuplus
      POSTGRES_PASSWORD: sovisuplus
      POSTGRES_DB: sovisuplus
    expose:
      - 5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - svp-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready  -d sovisuplus -U sovisuplus']
      interval: 1s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: svp-rabbitmq
    restart: always
    ports:
      - 5672:5672 # Default AMQP port
      - 15672:15672 # Management console
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - svp-network
    healthcheck:
      test: ['CMD-SHELL', 'rabbitmq-diagnostics -q ping']
      interval: 10s
      timeout: 5s
      retries: 5

  sovisuplus:
    image: crisalidesr/sovisuplus:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sovisuplus
    ports:
      - 3002:3000
      - 5555:5555
    environment:
      - DB_NAME=sovisuplus
      - DB_USER=sovisuplus
      - DB_PASSWORD=sovisuplus
      - DB_HOST=svp-db
      - DB_PORT=5432
      - NEXTAUTH_SECRET=include_your_secret_here
      - AMQP_HOST=svp-rabbitmq
      - AMQP_PORT=5672
      - AMQP_USER=guest
      - AMQP_PASSWORD=guest
      - AMQP_QUEUE_NAME=sovisuplus
      - AMQP_EXCHANGE_NAME=graph
      - GRAPHQL_ENDPOINT_ENABLED=false
      - GRAPHQL_API_KEY_ENABLED=false
    depends_on:
      svp-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - svp-network

networks:
  svp-network:
    driver: bridge
