query PeopleQuery($where: PersonWhere) {
  people(where: $where) {
    uid
    display_name
    external
    identifiers {
      type
      value
    }
    names {
      first_names {
        language
        value
      }
      last_names {
        language
        value
      }
    }

    membershipsConnection {
      edges {
        properties {
          start_date
          end_date
          position_code
        }
        node {
          uid
          external
          generic_type
          national_type
          types
          identifiers {
            type
            value
          }
          short_labels {
            language
            value
          }
          long_labels {
            language
            value
          }
        }
      }
    }
    employmentsConnection {
      edges {
        properties {
          start_date
          end_date
          position_code
        }
        node {
          uid
          external
          generic_type
          national_type
          types
          identifiers {
            type
            value
          }
          short_labels {
            language
            value
          }
          long_labels {
            language
            value
          }
        }
      }
    }
    recorded_by {
      uid
      name
      source
      source_identifier
      identifiers {
        type
        value
      }
    }
  }
}
